
package laporan;

import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

import koneksi.Koneksi;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import tampilan.dashboard3;

public class LaporanStokObat extends javax.swing.JPanel {
    private Connection conn = new Koneksi().connect();
    private dashboard3 dashboard;
    
    public LaporanStokObat(dashboard3 dashboard) {
        initComponents();
        this.dashboard = dashboard;
        loadDataObat("");
        
        tobat.getDocument().addDocumentListener(new DocumentListener() {
        @Override
        public void insertUpdate(DocumentEvent e) {
            cariObat();
        }

        @Override
        public void removeUpdate(DocumentEvent e) {
            cariObat();
        }

        @Override
        public void changedUpdate(DocumentEvent e) {
            cariObat();
        }
    });
        
 }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tobat = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableobat1 = new javax.swing.JTable();
        bkembali1 = new javax.swing.JButton();
        bcetak1 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(244, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1290, 930));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 28)); // NOI18N
        jLabel3.setText("Detail Laporan Stok Obat");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel4.setText("Nama Obat");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, 150, -1));

        tobat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(tobat, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 200, -1));

        tableobat1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No", "Nama Obat", "Kategori", "Satuan", "Harga", "Stok"
            }
        ));
        jScrollPane2.setViewportView(tableobat1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 689, 263));

        bkembali1.setBackground(new java.awt.Color(0, 153, 0));
        bkembali1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        bkembali1.setForeground(new java.awt.Color(255, 255, 255));
        bkembali1.setText("Kembali");
        bkembali1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bkembali1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkembali1ActionPerformed(evt);
            }
        });
        jPanel1.add(bkembali1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 110, 40));

        bcetak1.setBackground(new java.awt.Color(255, 51, 51));
        bcetak1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        bcetak1.setForeground(new java.awt.Color(255, 255, 255));
        bcetak1.setText("Cetak");
        bcetak1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bcetak1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcetak1ActionPerformed(evt);
            }
        });
        jPanel1.add(bcetak1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 430, 110, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1330, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bkembali1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkembali1ActionPerformed
        dashboard.showPanel(new PanelTampilLaporan(dashboard));
    }//GEN-LAST:event_bkembali1ActionPerformed

    private void bcetak1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcetak1ActionPerformed
        try {
            InputStream report = getClass().getResourceAsStream("/ireport/LaporanObat.jasper");

            if (report == null) {
                JOptionPane.showMessageDialog(null, "File LaporanObat.jasper tidak ditemukan!");
                return;
            }

            HashMap<String, Object> parameters = new HashMap<>();

            JasperPrint print = JasperFillManager.fillReport(report, parameters, conn);

            if (print.getPages().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Report kosong. Data tidak ditemukan dari database.");
                return;
            }

            JasperViewer viewer = new JasperViewer(print, false);
            viewer.setVisible(true);

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Gagal menampilkan report:\n" + e.getMessage());
        }
    }//GEN-LAST:event_bcetak1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bcetak1;
    private javax.swing.JButton bkembali1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableobat1;
    private javax.swing.JTextField tobat;
    // End of variables declaration//GEN-END:variables

    private void cariObat() {
    String keyword = tobat.getText().trim();
    loadDataObat(keyword);
  }
    
    private void loadDataObat(String keyword) {
    DefaultTableModel model = new DefaultTableModel(
        new Object[]{"No", "Nama Obat", "Kategori", "Satuan", "Harga", "Stok"},
        0
    ) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    String sql = "SELECT kd_obat, nm_obat, kategori, satuan, harga, stok "
               + "FROM obat "
               + "WHERE nm_obat LIKE ? OR kategori LIKE ? "
               + "ORDER BY CAST(kd_obat AS UNSIGNED) ASC";

    try {
        if (conn == null || conn.isClosed()) {
            conn = new Koneksi().connect();
        }

        PreparedStatement pst = conn.prepareStatement(sql);

        String cari = "%" + keyword + "%";

        pst.setString(1, cari); // cari berdasarkan nama obat
        pst.setString(2, cari); // cari berdasarkan kategori

        ResultSet rs = pst.executeQuery();

        int no = 1;

        while (rs.next()) {
            model.addRow(new Object[]{
                no++,
                rs.getString("nm_obat"),
                rs.getString("kategori"),
                rs.getString("satuan"),
                rs.getBigDecimal("harga"),
                rs.getInt("stok")
            });
        }

        tableobat1.setModel(model);

        rs.close();
        pst.close();

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(
            this,
            "Gagal menampilkan data obat: " + e.getMessage(),
            "Error",
            JOptionPane.ERROR_MESSAGE
        );
    }
  }

}
