
package laporan;

import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;

import koneksi.Koneksi;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import tampilan.dashboard3;

public class LaporanPemeriksaan extends javax.swing.JPanel {
    
    private Connection conn = new Koneksi().connect();
    private dashboard3 dashboard;
    
    public LaporanPemeriksaan(dashboard3 dashboard) {
        initComponents();
        this.dashboard = dashboard;
        
        loadDataPeriksa();

        tpasien.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                loadDataPeriksa();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                loadDataPeriksa();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                loadDataPeriksa();
            }
        });

        tanggal1.getDateEditor().addPropertyChangeListener("date", e -> {
            loadDataPeriksa();
        });

        tanggal2.getDateEditor().addPropertyChangeListener("date", e -> {
            loadDataPeriksa();
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablepemeriksaan = new javax.swing.JTable();
        bkembali = new javax.swing.JButton();
        bcetak1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tanggal2 = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        tanggal1 = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        tpasien = new javax.swing.JTextField();

        jPanel2.setBackground(new java.awt.Color(244, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1290, 930));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel4.setText("Nama Pasien");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, 150, -1));

        tablepemeriksaan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No", "Nama Pasien", "Nama Dokter", "Tanggal Periksa", "Diagnosa", "Tindakan"
            }
        ));
        jScrollPane2.setViewportView(tablepemeriksaan);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 689, 263));

        bkembali.setBackground(new java.awt.Color(0, 153, 0));
        bkembali.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        bkembali.setForeground(new java.awt.Color(255, 255, 255));
        bkembali.setText("Kembali");
        bkembali.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkembaliActionPerformed(evt);
            }
        });
        jPanel2.add(bkembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 110, 40));

        bcetak1.setBackground(new java.awt.Color(255, 51, 51));
        bcetak1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        bcetak1.setForeground(new java.awt.Color(255, 255, 255));
        bcetak1.setText("Cetak");
        bcetak1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bcetak1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcetak1ActionPerformed(evt);
            }
        });
        jPanel2.add(bcetak1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 430, 110, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("-");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 10, 30));
        jPanel2.add(tanggal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 120, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Periode :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 30));
        jPanel2.add(tanggal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 120, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 28)); // NOI18N
        jLabel5.setText("Detail Laporan Pemeriksaan Medis");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        tpasien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(tpasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 190, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkembaliActionPerformed
        dashboard.showPanel(new PanelTampilLaporan(dashboard));
    }//GEN-LAST:event_bkembaliActionPerformed

    private void bcetak1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcetak1ActionPerformed
        try {
        InputStream report = getClass().getResourceAsStream("/ireport/LaporanPemeriksaan.jasper");

        if (report == null) {
            JOptionPane.showMessageDialog(null, "File LaporanPemeriksaan.jasper tidak ditemukan!");
            return;
        }

        HashMap<String, Object> parameters = new HashMap<>();

        JasperPrint print = JasperFillManager.fillReport(report, parameters, conn);

        System.out.println("Jumlah halaman report: " + print.getPages().size());

        if (print.getPages().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Report kosong. Data tidak ditemukan.");
            return;
        }

        JasperViewer viewer = new JasperViewer(print, false);
        viewer.setVisible(true);

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Gagal menampilkan report:\n" + e.getMessage());
  }
    }//GEN-LAST:event_bcetak1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bcetak1;
    private javax.swing.JButton bkembali;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablepemeriksaan;
    private com.toedter.calendar.JDateChooser tanggal1;
    private com.toedter.calendar.JDateChooser tanggal2;
    private javax.swing.JTextField tpasien;
    // End of variables declaration//GEN-END:variables
    
    private void loadDataPeriksa() {
    DefaultTableModel model = new DefaultTableModel(
        new Object[]{"No", "Nama Pasien", "Nama Dokter", "Tanggal Periksa", "Diagnosa", "Tindakan"},
        0
    ) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    String keywordPasien = tpasien.getText().trim();
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

    StringBuilder sql = new StringBuilder();
    sql.append("SELECT ")
       .append("pr.id_periksa, ")
       .append("ps.nama_pasien, ")
       .append("dk.nama_dokter, ")
       .append("pr.tgl_periksa, ")
       .append("pr.diagnosa, ")
       .append("pr.tindakan ")
       .append("FROM periksa pr ")
       .append("INNER JOIN pasien ps ON pr.id_pasien = ps.id_pasien ")
       .append("INNER JOIN dokter dk ON pr.id_dokter = dk.id_dokter ")
       .append("WHERE 1=1 ");

    if (!keywordPasien.isEmpty()) {
        sql.append("AND ps.nama_pasien LIKE ? ");
    }

    if (tanggal1.getDate() != null && tanggal2.getDate() != null) {
        sql.append("AND DATE(pr.tgl_periksa) BETWEEN ? AND ? ");
    } else if (tanggal1.getDate() != null) {
        sql.append("AND DATE(pr.tgl_periksa) = ? ");
    } else if (tanggal2.getDate() != null) {
        sql.append("AND DATE(pr.tgl_periksa) = ? ");
    }

    sql.append("ORDER BY pr.tgl_periksa DESC, pr.id_periksa DESC");

    try {
        if (conn == null || conn.isClosed()) {
            conn = new Koneksi().connect();
        }

        PreparedStatement pst = conn.prepareStatement(sql.toString());

        int index = 1;

        if (!keywordPasien.isEmpty()) {
            pst.setString(index++, "%" + keywordPasien + "%");
        }

        if (tanggal1.getDate() != null && tanggal2.getDate() != null) {
            String tanggalAwal = sdf.format(tanggal1.getDate());
            String tanggalAkhir = sdf.format(tanggal2.getDate());

            pst.setString(index++, tanggalAwal);
            pst.setString(index++, tanggalAkhir);

        } else if (tanggal1.getDate() != null) {
            String tanggalAwal = sdf.format(tanggal1.getDate());
            pst.setString(index++, tanggalAwal);

        } else if (tanggal2.getDate() != null) {
            String tanggalAkhir = sdf.format(tanggal2.getDate());
            pst.setString(index++, tanggalAkhir);
        }

        ResultSet rs = pst.executeQuery();

        int no = 1;

        while (rs.next()) {
            model.addRow(new Object[]{
                no++,
                rs.getString("nama_pasien"),
                rs.getString("nama_dokter"),
                rs.getDate("tgl_periksa"),
                rs.getString("diagnosa"),
                rs.getString("tindakan")
            });
        }

        tablepemeriksaan.setModel(model);

        rs.close();
        pst.close();

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(
            this,
            "Gagal menampilkan data pemeriksaan: " + e.getMessage(),
            "Error",
            JOptionPane.ERROR_MESSAGE
        );
    }
}

}
