
package laporan;

import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.math.BigDecimal;
import java.text.NumberFormat;
import java.util.HashMap;
import java.util.Locale;

import koneksi.Koneksi;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import tampilan.dashboard3;

public class LaporanKeuangan extends javax.swing.JPanel {
    private Connection conn = new Koneksi().connect();
    private dashboard3 dashboard;
    
    public LaporanKeuangan(dashboard3 dashboard) {
        initComponents();
        this.dashboard = dashboard;
        loadDataKeuangan();
        
        jenis.addActionListener(e -> loadDataKeuangan());

        tanggal1.getDateEditor().addPropertyChangeListener("date", e -> {
            loadDataKeuangan();
        });
        
        tanggal2.getDateEditor().addPropertyChangeListener("date", e -> {
            loadDataKeuangan();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableobat1 = new javax.swing.JTable();
        bkembali = new javax.swing.JButton();
        bcetak1 = new javax.swing.JButton();
        jenis = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        tanggal2 = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        tanggal1 = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ltransaksi = new javax.swing.JLabel();
        lnominal = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(244, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1290, 930));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 28)); // NOI18N
        jLabel3.setText("Ringkasan Laporan");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel4.setText("Jenis Pembayaran");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 150, -1));

        tableobat1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No", "Nama Pasien", "Metode Pembayaran", "Jumlah Pembayaran", "Tanggal"
            }
        ));
        jScrollPane2.setViewportView(tableobat1);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 689, 263));

        bkembali.setBackground(new java.awt.Color(0, 153, 0));
        bkembali.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        bkembali.setForeground(new java.awt.Color(255, 255, 255));
        bkembali.setText("Kembali");
        bkembali.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkembaliActionPerformed(evt);
            }
        });
        jPanel2.add(bkembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 570, 110, 40));

        bcetak1.setBackground(new java.awt.Color(255, 51, 51));
        bcetak1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        bcetak1.setForeground(new java.awt.Color(255, 255, 255));
        bcetak1.setText("Cetak");
        bcetak1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bcetak1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcetak1ActionPerformed(evt);
            }
        });
        jPanel2.add(bcetak1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 570, 110, 40));

        jenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SEMUA", "BPJS", "TUNAI", "TRANSFER" }));
        jPanel2.add(jenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 190, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("-");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 10, 30));
        jPanel2.add(tanggal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 120, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Periode :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 30));
        jPanel2.add(tanggal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 120, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 28)); // NOI18N
        jLabel5.setText("Detail Laporan Keuangan (Pembayaran)");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setText("Total Transakasi :");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setText("Total Nominal :");

        ltransaksi.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lnominal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lnominal, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ltransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(468, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(ltransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lnominal, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 690, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkembaliActionPerformed
        dashboard.showPanel(new PanelTampilLaporan(dashboard));
    }//GEN-LAST:event_bkembaliActionPerformed

    private void bcetak1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcetak1ActionPerformed
        try {
            InputStream report = getClass().getResourceAsStream("/ireport/LaporanKeuangan.jasper");

            if (report == null) {
                JOptionPane.showMessageDialog(null, "File LaporanObat.jasper tidak ditemukan!");
                return;
            }

            HashMap<String, Object> parameters = new HashMap<>();

            JasperPrint print = JasperFillManager.fillReport(report, parameters, conn);

            if (print.getPages().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Report kosong. Data tidak ditemukan dari database.");
                return;
            }

            JasperViewer viewer = new JasperViewer(print, false);
            viewer.setVisible(true);

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Gagal menampilkan report:\n" + e.getMessage());
        }
    }//GEN-LAST:event_bcetak1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bcetak1;
    private javax.swing.JButton bkembali;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jenis;
    private javax.swing.JLabel lnominal;
    private javax.swing.JLabel ltransaksi;
    private javax.swing.JTable tableobat1;
    private com.toedter.calendar.JDateChooser tanggal1;
    private com.toedter.calendar.JDateChooser tanggal2;
    // End of variables declaration//GEN-END:variables
    
    private void loadDataKeuangan() {
    DefaultTableModel model = new DefaultTableModel(
        new Object[]{"No", "Nama Pasien", "Metode Pembayaran", "Jumlah Pembayaran", "Tanggal"},
        0
    ) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    String metode = jenis.getSelectedItem() != null
            ? jenis.getSelectedItem().toString()
            : "SEMUA";

    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

    StringBuilder sql = new StringBuilder();
    sql.append("SELECT ")
       .append("py.id_payment, ")
       .append("ps.nama_pasien, ")
       .append("py.metode_pembayaran, ")
       .append("py.jumlah_bayar, ")
       .append("py.tanggal_pembayaran ")
       .append("FROM payment py ")
       .append("INNER JOIN pasien ps ON py.id_pasien = ps.id_pasien ")
       .append("WHERE 1=1 ");

    if (!metode.equalsIgnoreCase("SEMUA")) {
        sql.append("AND py.metode_pembayaran = ? ");
    }

    if (tanggal1.getDate() != null && tanggal2.getDate() != null) {
        sql.append("AND DATE(py.tanggal_pembayaran) BETWEEN ? AND ? ");
    } else if (tanggal1.getDate() != null) {
        sql.append("AND DATE(py.tanggal_pembayaran) = ? ");
    } else if (tanggal2.getDate() != null) {
        sql.append("AND DATE(py.tanggal_pembayaran) = ? ");
    }

    sql.append("ORDER BY py.tanggal_pembayaran DESC");

    try {
        if (conn == null || conn.isClosed()) {
            conn = new Koneksi().connect();
        }

        PreparedStatement pst = conn.prepareStatement(sql.toString());

        int index = 1;

        if (!metode.equalsIgnoreCase("SEMUA")) {
            pst.setString(index++, metode);
        }

        if (tanggal1.getDate() != null && tanggal2.getDate() != null) {
            String tanggalAwal = sdf.format(tanggal1.getDate());
            String tanggalAkhir = sdf.format(tanggal2.getDate());

            pst.setString(index++, tanggalAwal);
            pst.setString(index++, tanggalAkhir);

        } else if (tanggal1.getDate() != null) {
            String tanggalAwal = sdf.format(tanggal1.getDate());
            pst.setString(index++, tanggalAwal);

        } else if (tanggal2.getDate() != null) {
            String tanggalAkhir = sdf.format(tanggal2.getDate());
            pst.setString(index++, tanggalAkhir);
        }

        ResultSet rs = pst.executeQuery();

        int no = 1;
        int totalTransaksi = 0;
        BigDecimal totalNominal = BigDecimal.ZERO;

        while (rs.next()) {
            BigDecimal jumlahBayar = rs.getBigDecimal("jumlah_bayar");

            if (jumlahBayar == null) {
                jumlahBayar = BigDecimal.ZERO;
            }

            model.addRow(new Object[]{
                no++,
                rs.getString("nama_pasien"),
                rs.getString("metode_pembayaran"),
                jumlahBayar,
                rs.getTimestamp("tanggal_pembayaran")
            });

            totalTransaksi++;
            totalNominal = totalNominal.add(jumlahBayar);
        }

        tableobat1.setModel(model);

        NumberFormat rupiahFormat = NumberFormat.getCurrencyInstance(new Locale("id", "ID"));

        ltransaksi.setText(String.valueOf(totalTransaksi));
        lnominal.setText(rupiahFormat.format(totalNominal));

        rs.close();
        pst.close();

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(
            this,
            "Gagal memfilter data keuangan: " + e.getMessage(),
            "Error",
            JOptionPane.ERROR_MESSAGE
        );
    }
}

}
