package laporan;

import tampilan.dashboard3;

public class PanelTampilLaporan extends javax.swing.JPanel {

    private dashboard3 dashboard;
    
    public PanelTampilLaporan(dashboard3 dashboard) {
        initComponents();
        this.dashboard = dashboard;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bstok = new javax.swing.JButton();
        bmedis = new javax.swing.JButton();
        bkunjungan = new javax.swing.JButton();
        bkeungan = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(244, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1366, 768));
        jPanel1.setMinimumSize(new java.awt.Dimension(1366, 768));
        jPanel1.setPreferredSize(new java.awt.Dimension(1290, 930));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 28)); // NOI18N
        jLabel1.setText("Pusat Laporan");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 190, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel2.setText("Pilih jenis laporan yang ingin anda lihat : ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 270, -1));

        bstok.setBackground(new java.awt.Color(0, 153, 0));
        bstok.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        bstok.setForeground(new java.awt.Color(255, 255, 255));
        bstok.setText("4. Stok Obat");
        bstok.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bstok.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bstok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bstokActionPerformed(evt);
            }
        });
        jPanel1.add(bstok, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 660, 40));

        bmedis.setBackground(new java.awt.Color(0, 153, 0));
        bmedis.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        bmedis.setForeground(new java.awt.Color(255, 255, 255));
        bmedis.setText("2. Pemeriksaan Medis");
        bmedis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bmedis.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bmedis.setMaximumSize(new java.awt.Dimension(244, 27));
        bmedis.setMinimumSize(new java.awt.Dimension(244, 27));
        bmedis.setPreferredSize(new java.awt.Dimension(244, 27));
        bmedis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmedisActionPerformed(evt);
            }
        });
        jPanel1.add(bmedis, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 660, 40));
        bmedis.getAccessibleContext().setAccessibleDescription("");

        bkunjungan.setBackground(new java.awt.Color(0, 153, 0));
        bkunjungan.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        bkunjungan.setForeground(new java.awt.Color(255, 255, 255));
        bkunjungan.setText("1. Kunjungan (Pendaftaran Pasien)");
        bkunjungan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bkunjungan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bkunjungan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkunjunganActionPerformed(evt);
            }
        });
        jPanel1.add(bkunjungan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 137, 660, 40));

        bkeungan.setBackground(new java.awt.Color(0, 153, 0));
        bkeungan.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        bkeungan.setForeground(new java.awt.Color(255, 255, 255));
        bkeungan.setText("3. Keungan (Pembayaran)");
        bkeungan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bkeungan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bkeungan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkeunganActionPerformed(evt);
            }
        });
        jPanel1.add(bkeungan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 660, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1330, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bstokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bstokActionPerformed
        dashboard.showPanel(new LaporanStokObat(dashboard));
    }//GEN-LAST:event_bstokActionPerformed

    private void bkeunganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkeunganActionPerformed
        dashboard.showPanel(new LaporanKeuangan(dashboard));
    }//GEN-LAST:event_bkeunganActionPerformed

    private void bmedisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmedisActionPerformed
        dashboard.showPanel(new LaporanPemeriksaan(dashboard));
    }//GEN-LAST:event_bmedisActionPerformed

    private void bkunjunganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkunjunganActionPerformed
         dashboard.showPanel(new LaporanKunjungan(dashboard));
    }//GEN-LAST:event_bkunjunganActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bkeungan;
    private javax.swing.JButton bkunjungan;
    private javax.swing.JButton bmedis;
    private javax.swing.JButton bstok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
