package tampilan;

/**
 *
 * @author Aldi
 */
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import koneksi.Koneksi;
import laporan.PanelTampilLaporan;

public class dashboard3 extends javax.swing.JFrame {

    /**
     * Creates new form dashboard3
     */
    public dashboard3() {
        initComponents();
        this.setLocationRelativeTo(null);
        panelContent.setLayout(new java.awt.BorderLayout());
        showPanel(new panelDashboard());
    }
    
    public void showPanel(javax.swing.JPanel panel) {
        panelContent.removeAll();
        panelContent.add(panel, java.awt.BorderLayout.CENTER);
        panelContent.revalidate();
        panelContent.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        panelSidebar = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        dashboard = new javax.swing.JLabel();
        dataDokter = new javax.swing.JLabel();
        dataLaporan = new javax.swing.JLabel();
        dataPasien = new javax.swing.JLabel();
        dataObat = new javax.swing.JLabel();
        dataPerawat = new javax.swing.JLabel();
        dataRuangan = new javax.swing.JLabel();
        dataPendaftaran = new javax.swing.JLabel();
        dataPemeriksaan = new javax.swing.JLabel();
        dataPembayaran = new javax.swing.JLabel();
        dataAdmin = new javax.swing.JLabel();
        keluar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        panelContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelMain.setBackground(new java.awt.Color(255, 255, 255));
        panelMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelSidebar.setBackground(new java.awt.Color(0, 102, 51));
        panelSidebar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel15.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Master Data");

        jLabel18.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Transaksi");

        jLabel19.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Sistem");

        dashboard.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        dashboard.setForeground(new java.awt.Color(255, 255, 255));
        dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/dashboard1 (1).png"))); // NOI18N
        dashboard.setText("Dashboard");
        dashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardMouseClicked(evt);
            }
        });

        dataDokter.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        dataDokter.setForeground(new java.awt.Color(255, 255, 255));
        dataDokter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/dokter1.png"))); // NOI18N
        dataDokter.setText("Data Dokter");
        dataDokter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dataDokter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataDokterMouseClicked(evt);
            }
        });

        dataLaporan.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        dataLaporan.setForeground(new java.awt.Color(255, 255, 255));
        dataLaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/laporan1.png"))); // NOI18N
        dataLaporan.setText("Laporan");
        dataLaporan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dataLaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataLaporanMouseClicked(evt);
            }
        });

        dataPasien.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        dataPasien.setForeground(new java.awt.Color(255, 255, 255));
        dataPasien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/pasien1.png"))); // NOI18N
        dataPasien.setText("Data Pasien");
        dataPasien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dataPasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataPasienMouseClicked(evt);
            }
        });

        dataObat.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        dataObat.setForeground(new java.awt.Color(255, 255, 255));
        dataObat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/obat1.png"))); // NOI18N
        dataObat.setText("Data Obat");
        dataObat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dataObat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataObatMouseClicked(evt);
            }
        });

        dataPerawat.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        dataPerawat.setForeground(new java.awt.Color(255, 255, 255));
        dataPerawat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/perawat1.png"))); // NOI18N
        dataPerawat.setText("Data Perawat");
        dataPerawat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dataPerawat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataPerawatMouseClicked(evt);
            }
        });

        dataRuangan.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        dataRuangan.setForeground(new java.awt.Color(255, 255, 255));
        dataRuangan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ruangan1.png"))); // NOI18N
        dataRuangan.setText("Data Ruangan");
        dataRuangan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dataRuangan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataRuanganMouseClicked(evt);
            }
        });

        dataPendaftaran.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        dataPendaftaran.setForeground(new java.awt.Color(255, 255, 255));
        dataPendaftaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/pemeriksaan1.png"))); // NOI18N
        dataPendaftaran.setText("Pendaftaran");
        dataPendaftaran.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dataPendaftaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataPendaftaranMouseClicked(evt);
            }
        });

        dataPemeriksaan.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        dataPemeriksaan.setForeground(new java.awt.Color(255, 255, 255));
        dataPemeriksaan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/pemeriksaan1.png"))); // NOI18N
        dataPemeriksaan.setText("Pemeriksaan");
        dataPemeriksaan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dataPemeriksaan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataPemeriksaanMouseClicked(evt);
            }
        });

        dataPembayaran.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        dataPembayaran.setForeground(new java.awt.Color(255, 255, 255));
        dataPembayaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/pembayaran1.png"))); // NOI18N
        dataPembayaran.setText("Pembayaran");
        dataPembayaran.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dataPembayaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataPembayaranMouseClicked(evt);
            }
        });

        dataAdmin.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        dataAdmin.setForeground(new java.awt.Color(255, 255, 255));
        dataAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/admin1.png"))); // NOI18N
        dataAdmin.setText("Admin");
        dataAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dataAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataAdminMouseClicked(evt);
            }
        });

        keluar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        keluar.setForeground(new java.awt.Color(255, 255, 255));
        keluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/keluar1.png"))); // NOI18N
        keluar.setText("Logout");
        keluar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        keluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                keluarMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logo2 (1).png"))); // NOI18N
        jLabel2.setText("HMS");

        javax.swing.GroupLayout panelSidebarLayout = new javax.swing.GroupLayout(panelSidebar);
        panelSidebar.setLayout(panelSidebarLayout);
        panelSidebarLayout.setHorizontalGroup(
            panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSidebarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSidebarLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dataDokter)
                            .addComponent(dataPasien)
                            .addComponent(dataObat)
                            .addComponent(dataPerawat)
                            .addComponent(dataRuangan)
                            .addComponent(dataPendaftaran)
                            .addComponent(dashboard))
                        .addGap(0, 64, Short.MAX_VALUE))
                    .addGroup(panelSidebarLayout.createSequentialGroup()
                        .addGroup(panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dataPemeriksaan)
                            .addComponent(dataPembayaran))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(panelSidebarLayout.createSequentialGroup()
                .addGroup(panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSidebarLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(dataLaporan))
                    .addGroup(panelSidebarLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(dataAdmin))
                    .addGroup(panelSidebarLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(keluar))
                    .addGroup(panelSidebarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel18)
                                .addComponent(jLabel15)
                                .addComponent(jLabel19)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelSidebarLayout.setVerticalGroup(
            panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSidebarLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dataDokter, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dataPerawat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dataPasien)
                .addGap(12, 12, 12)
                .addComponent(dataObat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dataRuangan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dataPendaftaran)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(dataPemeriksaan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dataPembayaran)
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addComponent(dataLaporan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dataAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(keluar)
                .addContainerGap(392, Short.MAX_VALUE))
        );

        panelMain.add(panelSidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 1000));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel4.setText("Hospital Management System");

        jSpinner1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jSpinner1.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.DAY_OF_WEEK_IN_MONTH));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logo1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 761, Short.MAX_VALUE)
                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        panelMain.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 1290, 70));

        panelContent.setPreferredSize(new java.awt.Dimension(1290, 930));
        panelContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelMain.add(panelContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, -1, -1));

        getContentPane().add(panelMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, 1000));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dataDokterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataDokterMouseClicked
      showPanel(new panelTampilDokter(this));
    }//GEN-LAST:event_dataDokterMouseClicked

    private void dataPasienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataPasienMouseClicked
      showPanel(new panelTampilPasien(this));
    }//GEN-LAST:event_dataPasienMouseClicked

    private void keluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_keluarMouseClicked
        loginFrame LF = new loginFrame();
        LF.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_keluarMouseClicked

    private void dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMouseClicked
        panelDashboard PD = new panelDashboard();
        showPanel(PD);
    }//GEN-LAST:event_dashboardMouseClicked

    private void dataPerawatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataPerawatMouseClicked
        showPanel(new panelTampilPerawat(this));
    }//GEN-LAST:event_dataPerawatMouseClicked

    private void dataObatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataObatMouseClicked
        showPanel(new panelTampilObat(this));
    }//GEN-LAST:event_dataObatMouseClicked

    private void dataPendaftaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataPendaftaranMouseClicked
        showPanel(new panelTampilPendaftaran(this));
    }//GEN-LAST:event_dataPendaftaranMouseClicked

    private void dataRuanganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataRuanganMouseClicked
        showPanel(new panelTampilRuangan(this));
    }//GEN-LAST:event_dataRuanganMouseClicked

    private void dataPemeriksaanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataPemeriksaanMouseClicked
        showPanel(new panelTampilPemeriksaan(this));
    }//GEN-LAST:event_dataPemeriksaanMouseClicked

    private void dataPembayaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataPembayaranMouseClicked
        showPanel(new panelTampilPembayaran(this));
    }//GEN-LAST:event_dataPembayaranMouseClicked

    private void dataLaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataLaporanMouseClicked
        showPanel(new PanelTampilLaporan(this));
    }//GEN-LAST:event_dataLaporanMouseClicked

    private void dataAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataAdminMouseClicked
        showPanel(new panelTampilAdmin(this));
    }//GEN-LAST:event_dataAdminMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dashboard;
    private javax.swing.JLabel dataAdmin;
    private javax.swing.JLabel dataDokter;
    private javax.swing.JLabel dataLaporan;
    private javax.swing.JLabel dataObat;
    private javax.swing.JLabel dataPasien;
    private javax.swing.JLabel dataPembayaran;
    private javax.swing.JLabel dataPemeriksaan;
    private javax.swing.JLabel dataPendaftaran;
    private javax.swing.JLabel dataPerawat;
    private javax.swing.JLabel dataRuangan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel keluar;
    private javax.swing.JPanel panelContent;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelSidebar;
    // End of variables declaration//GEN-END:variables
}
