/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tampilan;

/**
 *
 * @author Aldi
 */
import java.sql.*;
import javax.swing.JOptionPane;
import koneksi.Koneksi;
public class loginFrame extends javax.swing.JFrame {
private Connection conn = new Koneksi().connect();


    /**
     * Creates new form loginFrame
     */
    public loginFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        blogin = new javax.swing.JButton();
        txtid = new javax.swing.JTextField();
        blogin2 = new javax.swing.JButton();
        bregister = new javax.swing.JButton();
        txtpass = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("ID Admin");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 206, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Password");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 292, -1, -1));

        blogin.setBackground(new java.awt.Color(0, 153, 51));
        blogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        blogin.setForeground(new java.awt.Color(255, 255, 255));
        blogin.setText("Login");
        blogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        blogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloginActionPerformed(evt);
            }
        });
        jPanel2.add(blogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, 340, 39));
        jPanel2.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 232, 577, 42));

        blogin2.setBackground(new java.awt.Color(0, 153, 51));
        blogin2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        blogin2.setForeground(new java.awt.Color(255, 255, 255));
        blogin2.setText("Login");
        blogin2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        blogin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blogin2ActionPerformed(evt);
            }
        });
        jPanel2.add(blogin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 128, 274, 46));

        bregister.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bregister.setText("Daftar");
        bregister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bregisterActionPerformed(evt);
            }
        });
        jPanel2.add(bregister, new org.netbeans.lib.awtextra.AbsoluteConstraints(527, 128, 266, 46));

        txtpass.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jPanel2.add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 330, 577, 51));

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("CLOSE");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 460, 100, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloginActionPerformed
         try {
            String sql = "SELECT * FROM admin WHERE id_admin ='"+txtid.getText()+"' AND password='"+txtpass.getText()+"'";
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);

            if(hasil.next()) {
                UserID.setUserLogin(hasil.getString("id_admin"));
                JOptionPane.showMessageDialog(null, "Berhasil Login");

                this.setVisible(false);
                new dashboard3().setVisible(true);

            } else {
                JOptionPane.showMessageDialog(null, "Username atau Password Salah");
            }

        } catch(SQLException e) {
            JOptionPane.showMessageDialog(null, "Gagal Login !!!" + e);
        }
    }//GEN-LAST:event_bloginActionPerformed

    private void bregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bregisterActionPerformed
        register r = new register();
        r.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bregisterActionPerformed

    private void blogin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blogin2ActionPerformed
       JOptionPane.showMessageDialog(null, "Anda Sudah Berada di Form Login");
    }//GEN-LAST:event_blogin2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton blogin;
    private javax.swing.JButton blogin2;
    private javax.swing.JButton bregister;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtid;
    private javax.swing.JPasswordField txtpass;
    // End of variables declaration//GEN-END:variables
}
