/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tampilan;

/**
 *
 * @author Aldi
 */
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.Koneksi;
public class panelTampilRuangan extends javax.swing.JPanel {
    private dashboard3 dashboard;
    private Connection conn = new Koneksi().connect();
    private DefaultTableModel tabmode;
    /**
     * Creates new form panelTampilRuangan
     */
    public panelTampilRuangan(dashboard3 dashboard) {
        initComponents();
        this.dashboard = dashboard;
        datatable();
    }
    
     protected void datatable() {
        Object[] Baris = {"Kode Ruangan", "Nama Ruangan", "Jenis Ruangan", "Lantai", "Kapasitas", "Fasilitas","Status"};
        tabmode = new DefaultTableModel(null, Baris);
        tabelruangan.setModel(tabmode);
        String sql = "select * from ruangan where 1=1";
        if (!kdruangan.getText().isEmpty()) {
            sql += " and kd_ruangan like '%" + kdruangan.getText() + "%'";
        }
        if (!nmruangan.getText().isEmpty()) {
            sql += " and nama_ruangan like '%" + nmruangan.getText() + "%'";
        }
        if (jenis.getSelectedIndex() > 0) {
            sql += " and jenis = '" + jenis.getSelectedItem().toString() + "'";
        }
        if (lantai.getValue() instanceof Integer && (Integer) lantai.getValue() > 0) {
            sql += " and lantai = '" + lantai.getValue().toString() + "'";
        }
        try {
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()) {
                tabmode.addRow(new Object[]{
                    hasil.getString("kd_ruangan"),
                    hasil.getString("nama_ruangan"),
                    hasil.getString("jenis"),
                    hasil.getString("lantai"),
                    hasil.getString("kapasitas"),
                    hasil.getString("fasilitas"),
                    hasil.getString("status")
                });               
            }
            tabelruangan.setModel(tabmode);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "data gagal dipanggil" + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        kdruangan = new javax.swing.JTextField();
        btambah = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelruangan = new javax.swing.JTable();
        bcari = new javax.swing.JButton();
        bubah = new javax.swing.JButton();
        bhapus = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        nmruangan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jenis = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        lantai = new javax.swing.JSpinner();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(244, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1366, 768));
        jPanel1.setMinimumSize(new java.awt.Dimension(1366, 768));
        jPanel1.setPreferredSize(new java.awt.Dimension(705, 441));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 28)); // NOI18N
        jLabel1.setText("Data Ruangan");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel2.setText("Kode Ruangan");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 116, -1));

        kdruangan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        kdruangan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                kdruanganKeyPressed(evt);
            }
        });
        jPanel1.add(kdruangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 116, -1));

        btambah.setBackground(new java.awt.Color(0, 153, 0));
        btambah.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btambah.setForeground(new java.awt.Color(255, 255, 255));
        btambah.setText("Tambah Data Ruangan");
        btambah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btambahActionPerformed(evt);
            }
        });
        jPanel1.add(btambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        tabelruangan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tabelruangan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Kd Ruangan", "Nama Ruangan", "Jenis Ruangan", "Lantai", "Kapasitas", "Fasilitas", "Status"
            }
        ));
        jScrollPane1.setViewportView(tabelruangan);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 830, 263));

        bcari.setBackground(new java.awt.Color(0, 153, 0));
        bcari.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bcari.setForeground(new java.awt.Color(255, 255, 255));
        bcari.setText("Terapkan Filter");
        bcari.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcariActionPerformed(evt);
            }
        });
        jPanel1.add(bcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 140, -1, -1));

        bubah.setBackground(new java.awt.Color(0, 153, 0));
        bubah.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        bubah.setForeground(new java.awt.Color(255, 255, 255));
        bubah.setText("Ubah");
        bubah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bubahActionPerformed(evt);
            }
        });
        jPanel1.add(bubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, -1, -1));

        bhapus.setBackground(new java.awt.Color(255, 51, 51));
        bhapus.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        bhapus.setForeground(new java.awt.Color(255, 255, 255));
        bhapus.setText("Hapus");
        bhapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhapusActionPerformed(evt);
            }
        });
        jPanel1.add(bhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel3.setText("Nama Ruangan");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, -1, -1));

        nmruangan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nmruangan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nmruanganKeyPressed(evt);
            }
        });
        jPanel1.add(nmruangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 164, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel4.setText("Jenis Ruangan");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 100, -1));

        jenis.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih Jenis Ruangan--", "Rawat Inap", "Poliklinik", "IGD", "Kritis", "Operasi" }));
        jPanel1.add(jenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel6.setText("Lantai");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, 50, -1));

        lantai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lantai.setModel(new javax.swing.SpinnerNumberModel(0, 0, 4, 1));
        jPanel1.add(lantai, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, 100, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 950));
    }// </editor-fold>//GEN-END:initComponents

    private void kdruanganKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kdruanganKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            datatable();
        }
    }//GEN-LAST:event_kdruanganKeyPressed

    private void btambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btambahActionPerformed
        dashboard.showPanel(new panelTambahRuangan(dashboard));
    }//GEN-LAST:event_btambahActionPerformed

    private void bcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcariActionPerformed
        // TODO add your handling code here:
        datatable();
    }//GEN-LAST:event_bcariActionPerformed

    private void bubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bubahActionPerformed
        // TODO add your handling code here:
        int bar = tabelruangan.getSelectedRow();
        if (bar == -1) {
            JOptionPane.showMessageDialog(null, "pilih data ruangan yang ingin diubah");
            return;
        }
        panelEditRuangan panel = new panelEditRuangan(dashboard);
        panel.setRuangan(
            tabmode.getValueAt(bar, 0).toString(),
            tabmode.getValueAt(bar, 1).toString(),
            tabmode.getValueAt(bar, 2).toString(),
            tabmode.getValueAt(bar, 3).toString(),
            tabmode.getValueAt(bar, 4).toString(),
            tabmode.getValueAt(bar, 5).toString(),
            tabmode.getValueAt(bar, 6).toString()
        );
        dashboard.showPanel(panel);
    }//GEN-LAST:event_bubahActionPerformed

    private void bhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapusActionPerformed
        // TODO add your handling code here:
        int bar = tabelruangan.getSelectedRow();
        if (bar == -1) {
            JOptionPane.showMessageDialog(null, "pilih data ruangan yang ingin dihapus");
            return;
        }
        String id = tabmode.getValueAt(bar, 0).toString();
        int ok = JOptionPane.showConfirmDialog(null, "hapus data ruangan " + id + " ?", "konfirmasi dialog",
            JOptionPane.YES_NO_OPTION);
        if (ok == 0) {
            String sql = "delete from ruangan where kd_ruangan = ?";
            try {
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.setString(1, id);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "data berhasil dihapus");
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "data gagal dihapus" + e);
            }
            datatable();
        }
    }//GEN-LAST:event_bhapusActionPerformed

    private void nmruanganKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nmruanganKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_nmruanganKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bcari;
    private javax.swing.JButton bhapus;
    private javax.swing.JButton btambah;
    private javax.swing.JButton bubah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jenis;
    private javax.swing.JTextField kdruangan;
    private javax.swing.JSpinner lantai;
    private javax.swing.JTextField nmruangan;
    private javax.swing.JTable tabelruangan;
    // End of variables declaration//GEN-END:variables
}
