/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tampilan;

import java.sql.Connection;
import koneksi.Koneksi;

/**
 *
 * @author Aldi
 */
import java.sql.*;
import javax.swing.JOptionPane;
import koneksi.Koneksi;
public class panelEditAdmin extends javax.swing.JPanel {
    private dashboard3 dashboard;
    private Connection conn = new Koneksi().connect();
    /**
     * Creates new form panelEditAdmin
     */
    public panelEditAdmin(dashboard3 dashboard) {
        initComponents();
        this.dashboard = dashboard;
    }
    
     public void setData(String id, String nama, String email, String password){

    txtid.setText(id);
    txtnm.setText(nama);
    txtemail.setText(email);
    txtpass.setText(password);

    txtid.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bsimpan = new javax.swing.JButton();
        bbatal = new javax.swing.JButton();
        bkembali = new javax.swing.JButton();
        txtid = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txtnm = new javax.swing.JTextField();
        txtpass = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(228, 224, 224));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("ID Admin");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Nama");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Email");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("Password");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 250, -1, -1));

        bsimpan.setBackground(new java.awt.Color(0, 153, 51));
        bsimpan.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        bsimpan.setForeground(new java.awt.Color(255, 255, 255));
        bsimpan.setText("Simpan");
        bsimpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsimpanActionPerformed(evt);
            }
        });
        jPanel3.add(bsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 400, -1, 31));

        bbatal.setBackground(new java.awt.Color(255, 51, 51));
        bbatal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        bbatal.setForeground(new java.awt.Color(255, 255, 255));
        bbatal.setText("Batal");
        bbatal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbatalActionPerformed(evt);
            }
        });
        jPanel3.add(bbatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 400, -1, 31));

        bkembali.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        bkembali.setText("Kembali");
        bkembali.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkembaliActionPerformed(evt);
            }
        });
        jPanel3.add(bkembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 400, -1, 31));

        txtid.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel3.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 410, 40));

        txtemail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel3.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 170, 410, 40));

        txtnm.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel3.add(txtnm, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 410, 40));

        txtpass.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel3.add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 300, 410, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Edit Data Admin");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, -1, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 1130));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, -3, 1370, 1230));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 950));
    }// </editor-fold>//GEN-END:initComponents

    private void bsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpanActionPerformed
         String idAdmin = txtid.getText().trim();
         String email = txtemail.getText().trim();
         String nama = txtnm.getText().trim();
         String password = txtpass.getText();
         
          if (idAdmin.isEmpty() || email.isEmpty() || nama.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua bidang data harus diisi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
          
          String sql = "UPDATE admin SET email = ?, nama = ?, password = ? WHERE id_admin = ?";
          
          Koneksi konek = new Koneksi();
          Connection conn = konek.connect();
          
          if(conn == null) {
              JOptionPane.showMessageDialog(this,
                      "Gagal Terhubung ke Database",
                      "Error",
                      JOptionPane.ERROR_MESSAGE);
              return;
          }
          
          try(PreparedStatement ps = conn.prepareStatement(sql)) {
              ps.setString(1, email);
              ps.setString(2, nama);
              ps.setString(3, password);
              ps.setString(4, idAdmin);
              
              int rowsUpdate = ps.executeUpdate();
              
              if(rowsUpdate > 0) {
                  JOptionPane.showMessageDialog(this, 
                            "Data Admin Berhasil di Perbarui",
                            "Sukses",
                            JOptionPane.INFORMATION_MESSAGE);
                  
                  dashboard.showPanel(new panelTampilAdmin(dashboard));
              } else {
                  JOptionPane.showMessageDialog(this,
                          "ID Admin Tidak Ditemukan",
                          "Peringatan",
                          JOptionPane.WARNING_MESSAGE);
              }
          } catch(SQLException e) {
              JOptionPane.showMessageDialog(this,
             "Gagal Memperbarui Data " + e.getMessage());
          } finally {
              try {
                  if(conn != null) {
                      conn.close();
                  }
              } catch(SQLException e) {
                  e.printStackTrace();
              }
          }

    }//GEN-LAST:event_bsimpanActionPerformed

    private void bbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbatalActionPerformed
        txtemail.setText("");
        txtnm.setText("");
        txtpass.setText("");
        txtnm.requestFocus();
    }//GEN-LAST:event_bbatalActionPerformed

    private void bkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkembaliActionPerformed
        dashboard.showPanel(new panelTampilAdmin(dashboard));
    }//GEN-LAST:event_bkembaliActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bbatal;
    private javax.swing.JButton bkembali;
    private javax.swing.JButton bsimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnm;
    private javax.swing.JTextField txtpass;
    // End of variables declaration//GEN-END:variables
}
