/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tampilan;

/**
 *
 * @author Aldi
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.Koneksi;

public class panelTampilAdmin extends javax.swing.JPanel {
    private dashboard3 dashboard;
    private Connection conn = new Koneksi().connect();
    private DefaultTableModel tabmode;
    /**
     * Creates new form panelTampilAdmin
     */
    public panelTampilAdmin(dashboard3 dashboard) {
        initComponents();
        this.dashboard = dashboard;
        
        loadDataAdmin();
    }
    
   public void loadDataAdmin() {

    DefaultTableModel model = (DefaultTableModel) tableAdmin.getModel();
    model.setRowCount(0);

    String sql = "SELECT id_admin, nama, email FROM admin";

    Koneksi konek = new Koneksi();
    Connection conn = konek.connect();

    try (PreparedStatement ps = conn.prepareStatement(sql);
         ResultSet rs = ps.executeQuery()) {

        while (rs.next()) {

            model.addRow(new Object[]{
                rs.getString("id_admin"),
                rs.getString("nama"),
                rs.getString("email")
            });

        }

    } catch (SQLException ex) {

        JOptionPane.showMessageDialog(this,
                "Gagal memuat data : " + ex.getMessage());

    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAdmin = new javax.swing.JTable();
        btambah = new javax.swing.JButton();
        bhapus = new javax.swing.JButton();
        bedit = new javax.swing.JButton();

        setBackground(new java.awt.Color(244, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Manajemen Admin");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Daftar Admin");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addContainerGap(747, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 900, -1));

        jScrollPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        tableAdmin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tableAdmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID Admin", "Nama", "Email"
            }
        ));
        tableAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableAdminMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableAdmin);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 900, 450));

        btambah.setBackground(new java.awt.Color(0, 153, 51));
        btambah.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btambah.setForeground(new java.awt.Color(255, 255, 255));
        btambah.setText("+ Tambah Admin Baru");
        btambah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btambahActionPerformed(evt);
            }
        });
        add(btambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 650, -1, 30));

        bhapus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bhapus.setText("Hapus Data Admin");
        bhapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhapusActionPerformed(evt);
            }
        });
        add(bhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 650, -1, -1));

        bedit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bedit.setText("Edit");
        bedit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beditActionPerformed(evt);
            }
        });
        add(bedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 650, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void tableAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableAdminMouseClicked
        
    }//GEN-LAST:event_tableAdminMouseClicked

    private void bhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapusActionPerformed
          int selectedRow = tableAdmin.getSelectedRow();

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this,
                "Silakan pilih salah satu data admin di tabel terlebih dahulu!",
                "Peringatan",
                JOptionPane.WARNING_MESSAGE);
        return;
    }

    String idAdmin = tableAdmin.getValueAt(selectedRow, 0).toString();
    String namaAdmin = tableAdmin.getValueAt(selectedRow, 1).toString();

    int konfirmasi = JOptionPane.showConfirmDialog(
            this,
            "Apakah anda yakin ingin menghapus data admin: "
            + namaAdmin + " (ID: " + idAdmin + ")?",
            "Konfirmasi Hapus Data",
            JOptionPane.YES_NO_OPTION);

    if (konfirmasi == JOptionPane.YES_OPTION) {

        String sql = "DELETE FROM admin WHERE id_admin = ?";

        Koneksi konek = new Koneksi();

        try (Connection conn = konek.connect();
             PreparedStatement ps = conn.prepareStatement(sql)) {

            ps.setString(1, idAdmin);

            int hasil = ps.executeUpdate();

            if (hasil > 0) {
                JOptionPane.showMessageDialog(this,
                        "Data admin berhasil dihapus!");

                loadDataAdmin();

            } else {
                JOptionPane.showMessageDialog(this,
                        "Data tidak ditemukan!");
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,
                    "Terjadi kesalahan: " + ex.getMessage());
        }
    }
    }//GEN-LAST:event_bhapusActionPerformed

    private void beditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beditActionPerformed
        int baris = tableAdmin.getSelectedRow();

        if(baris == -1){
            JOptionPane.showMessageDialog(null,"Pilih data yang akan diubah!");
            return;
        }
        String idAdmin = tableAdmin.getValueAt(baris, 0).toString();
        String sql = "SELECT * FROM admin WHERE id_admin = ?";
        
        try (PreparedStatement ps = conn.prepareStatement(sql)) {

        ps.setString(1, idAdmin);

        ResultSet rs = ps.executeQuery();

        if (rs.next()) {

            panelEditAdmin panel = new panelEditAdmin(dashboard);

            panel.setData(
                    rs.getString("id_admin"),
                    rs.getString("nama"),
                    rs.getString("email"),
                    rs.getString("password")
            );

            dashboard.showPanel(panel);

        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this,
                "Gagal mengambil data: " + e.getMessage());
    }
    }//GEN-LAST:event_beditActionPerformed

    private void btambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btambahActionPerformed
        dashboard.showPanel(new panelTambahAdmin(dashboard));
    }//GEN-LAST:event_btambahActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bedit;
    private javax.swing.JButton bhapus;
    private javax.swing.JButton btambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tableAdmin;
    // End of variables declaration//GEN-END:variables
}
