/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tampilan;

/**
 *
 * @author Aldi
 */
import java.sql.*;
import javax.swing.JOptionPane;
import koneksi.Koneksi;
public class panelTambahDokter extends javax.swing.JPanel {
private dashboard3 dashboard;
private Connection conn = new Koneksi().connect();
    /**
     * Creates new form panelTambahDokter
     */
    public panelTambahDokter(dashboard3 dashboard) {
        initComponents();
        isispesialis();
        kosong();
        aktif();
        
        this.dashboard = dashboard;
    }
    
    protected void aktif(){
        tkddokter.requestFocus();
    }
    
    protected void kosong(){
        tkddokter.setText("");
        tnmdokter.setText("");
        tnotelp.setText("");
        talamat.setText("");
        buttonGroup1.clearSelection();
        cbspesialis.setSelectedIndex(0);
    }
    
    protected void isispesialis(){
        cbspesialis.removeAllItems();
        cbspesialis.addItem("Spesialis Anak");
        cbspesialis.addItem("Spesialis Bedah");
        cbspesialis.addItem("Spesialis Kandungan");
        cbspesialis.addItem("Spesialis Gigi");
        cbspesialis.addItem("Spesialis Penyakit Dalam");
        cbspesialis.addItem("Spesialis Mata");
        cbspesialis.addItem("Spesialis THT");
        cbspesialis.addItem("Spesialis Kulit dan Kelamin");
        cbspesialis.addItem("Spesialis Jantung");
        cbspesialis.addItem("Spesialis Saraf");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tkddokter = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tnmdokter = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbspesialis = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        rblaki = new javax.swing.JRadioButton();
        rbperempuan = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        talamat = new javax.swing.JTextArea();
        bsimpan = new javax.swing.JButton();
        bbatal = new javax.swing.JButton();
        tnotelp = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(244, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1366, 768));
        jPanel1.setMinimumSize(new java.awt.Dimension(1366, 768));
        jPanel1.setPreferredSize(new java.awt.Dimension(559, 331));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 28)); // NOI18N
        jLabel1.setText("Tambah Data Dokter Baru");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 340, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel2.setText("ID Dokter");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 180, -1));

        tkddokter.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(tkddokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 180, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel3.setText("Nama Dokter");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 180, -1));

        tnmdokter.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(tnmdokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 180, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel4.setText("Spesialis");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 100, -1));

        cbspesialis.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbspesialis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semua Spesialis", "Spesialis Anak", "Spesialis Bedah", "Spesialis Penyakit Dalam", "Spesialis Kandungan", "Spesialis Gigi", "Spesialis Mata", "Spesialis THT", "Spesialis Kulit dan Kelamin", "Spesialis Jantung", "Spesialis Saraf", " " }));
        jPanel1.add(cbspesialis, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 180, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel5.setText("Jenis Kelamin");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 100, -1));

        buttonGroup1.add(rblaki);
        rblaki.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        rblaki.setText("Laki-Laki");
        jPanel1.add(rblaki, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 98, -1));

        buttonGroup1.add(rbperempuan);
        rbperempuan.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        rbperempuan.setText("Perempuan");
        jPanel1.add(rbperempuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 110, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel6.setText("No. Telp");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 100, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel7.setText("Alamat");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 100, 20));

        talamat.setColumns(20);
        talamat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        talamat.setRows(5);
        jScrollPane1.setViewportView(talamat);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 242, -1));

        bsimpan.setBackground(new java.awt.Color(0, 153, 0));
        bsimpan.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        bsimpan.setForeground(new java.awt.Color(255, 255, 255));
        bsimpan.setText("Simpan");
        bsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsimpanActionPerformed(evt);
            }
        });
        jPanel1.add(bsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));

        bbatal.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        bbatal.setText("Batal");
        bbatal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbatalActionPerformed(evt);
            }
        });
        jPanel1.add(bbatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, -1, -1));

        tnotelp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(tnotelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 180, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1330, 960));
    }// </editor-fold>//GEN-END:initComponents

    private void bsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpanActionPerformed
        // TODO add your handling code here:
        String jenis = null;
        if (rblaki.isSelected()){
            jenis = "Laki-Laki";
        } else if (rbperempuan.isSelected()){
            jenis = "Perempuan";
        }
        String sql = "insert into dokter (id_dokter, nama_dokter, no_hp, spesialis, alamat, jenis_kelamin) values (?,?,?,?,?,?)";
        try {
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, tkddokter.getText());
            stat.setString(2, tnmdokter.getText());
            stat.setString(3, tnotelp.getText());
            stat.setString(4, (String)cbspesialis.getSelectedItem());
            stat.setString(5, talamat.getText());
            stat.setString(6, jenis);

            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "data berhasil disimpan");
            tkddokter.requestFocus();
            
            dashboard.showPanel(new panelTampilDokter(dashboard));
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "data gagal disimpan" + e);
        }
    }//GEN-LAST:event_bsimpanActionPerformed

    private void bbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbatalActionPerformed
        dashboard.showPanel(new panelTampilDokter(dashboard));
        kosong();
        tkddokter.requestFocus();
    }//GEN-LAST:event_bbatalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bbatal;
    private javax.swing.JButton bsimpan;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbspesialis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rblaki;
    private javax.swing.JRadioButton rbperempuan;
    private javax.swing.JTextArea talamat;
    private javax.swing.JTextField tkddokter;
    private javax.swing.JTextField tnmdokter;
    private javax.swing.JTextField tnotelp;
    // End of variables declaration//GEN-END:variables
}
