/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tampilan;

/**
 *
 * @author Aldi
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import koneksi.Koneksi;
import javax.swing.table.DefaultTableModel;
import java.util.HashMap;
import java.util.Map;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

public class panelTampilPemeriksaan extends javax.swing.JPanel {
    private dashboard3 dashboard;
    Connection conn = new Koneksi().connect();
    PreparedStatement pst;
    ResultSet rs;
    private String idPeriksa = "";
    /**
     * Creates new form panelTampilPemeriksaan
     */
    public panelTampilPemeriksaan(dashboard3 dashboard) {
        initComponents();
        this.dashboard = dashboard;
        tampilData();
    }
    
    private void tampilData(){

     DefaultTableModel model = new DefaultTableModel();

    model.addColumn("No Pemeriksaan");
    model.addColumn("Tanggal");
    model.addColumn("No Pasien");
    model.addColumn("Nama Pasien");
    model.addColumn("Nama Dokter");
    model.addColumn("Diagnosis");
    model.addColumn("Tindakan");

    try{

        String sql =
        "SELECT periksa.id_periksa, periksa.tgl_periksa, " +
        "pasien.id_pasien, pasien.nama_pasien, " +
        "dokter.nama_dokter, periksa.diagnosa, periksa.tindakan " +
        "FROM periksa " +
        "JOIN pasien ON pasien.id_pasien = periksa.id_pasien " +
        "JOIN dokter ON dokter.id_dokter = periksa.id_dokter";

        pst = conn.prepareStatement(sql);

        rs = pst.executeQuery();

        while(rs.next()){

            model.addRow(new Object[]{
                rs.getString("id_periksa"),
                rs.getString("tgl_periksa"),
                rs.getString("id_pasien"),
                rs.getString("nama_pasien"),
                rs.getString("nama_dokter"),
                rs.getString("diagnosa"),
                rs.getString("tindakan")
            });

        }

        tblPeriksa.setModel(model);

    }catch(Exception e){
    e.printStackTrace();
    JOptionPane.showMessageDialog(null, e.getMessage());

    }

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnTambah = new javax.swing.JButton();
        btnCetak = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPeriksa = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(244, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel2.setText("Hospital Management System");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 19, -1, 36));

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel1.setText("Pemeriksaan");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 73, 167, 27));

        btnTambah.setBackground(new java.awt.Color(0, 153, 0));
        btnTambah.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setText("Tambah Pemeriksaan Baru");
        btnTambah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        jPanel1.add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 131, -1, -1));

        btnCetak.setBackground(new java.awt.Color(0, 102, 225));
        btnCetak.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnCetak.setForeground(new java.awt.Color(255, 255, 255));
        btnCetak.setText("Cetak");
        btnCetak.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });
        jPanel1.add(btnCetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 150, 80, 30));

        btnEdit.setBackground(new java.awt.Color(0, 153, 0));
        btnEdit.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Edit");
        btnEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel1.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 92, 30));

        btnHapus.setBackground(new java.awt.Color(255, 51, 51));
        btnHapus.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("Hapus");
        btnHapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jPanel1.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 92, 30));

        tblPeriksa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "No Pemeriksaan", "Tanggal ", "No Pasien", "Nama Pasien", "Nama Dokter", "Diagnosis Awal", "Tindakan Lanjut"
            }
        ));
        tblPeriksa.setColumnSelectionAllowed(true);
        tblPeriksa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPeriksaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPeriksa);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 192, 1009, 471));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 950));
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        dashboard.showPanel(new panelTambahPemeriksaan(dashboard));
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed

        try {

            if (conn == null || conn.isClosed()) {
                conn = new Koneksi().connect();
            }

            JasperReport jr = JasperCompileManager.compileReport(
                getClass().getResourceAsStream("/ireport/pemeriksaan.jrxml")
            );

            Map<String, Object> param = new HashMap<>();
            JasperPrint jp = JasperFillManager.fillReport(jr, param, conn);
            JasperViewer.viewReport(jp, false);

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Gagal mencetak laporan: " + e.getMessage());
        }
    }//GEN-LAST:event_btnCetakActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed

       int baris = tblPeriksa.getSelectedRow();

        if (baris == -1) {
            JOptionPane.showMessageDialog(this,
                "Pilih data terlebih dahulu!");
            return;
        }

        String idPeriksa = tblPeriksa.getValueAt(baris, 0).toString();

        dashboard.showPanel(new panelEditPemeriksaan(dashboard, idPeriksa));

    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed

      if (idPeriksa.equals("")) {

    JOptionPane.showMessageDialog(null,
            "Pilih data terlebih dahulu!");

    return;
}

int jawab = JOptionPane.showConfirmDialog(
        null,
        "Hapus data ini?",
        "Konfirmasi",
        JOptionPane.YES_NO_OPTION);

if (jawab == JOptionPane.YES_OPTION) {

    try {

        String sql = "DELETE FROM periksa WHERE id_periksa=?";

        pst = conn.prepareStatement(sql);

        pst.setString(1, idPeriksa);
     

        pst.executeUpdate();

        JOptionPane.showMessageDialog(null,
                "Data berhasil dihapus");

        tampilData();

        idPeriksa = "";

    } catch(Exception e){
    e.printStackTrace();
    JOptionPane.showMessageDialog(null, e.getMessage());

    }
}
    }//GEN-LAST:event_btnHapusActionPerformed

    private void tblPeriksaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPeriksaMouseClicked
      int baris = tblPeriksa.getSelectedRow();

        idPeriksa = tblPeriksa.getValueAt(baris,0).toString();
    }//GEN-LAST:event_tblPeriksaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPeriksa;
    // End of variables declaration//GEN-END:variables
}
