/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tampilan;

/**
 *
 * @author Aldi
 */
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.event.KeyEvent;
import java.io.InputStream;
import java.util.HashMap;
import koneksi.Koneksi;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
public class panelTampilPasien extends javax.swing.JPanel {
    private dashboard3 dashboard;
    private Connection conn = new Koneksi().connect();
    private panelTampilPembayaran panelPembayaran;
    private DefaultTableModel tabmode;
    /**
     * Creates new form panelTampilPasien
     */
    public panelTampilPasien(dashboard3 dashboard, panelTampilPembayaran panelPembayaran) {
        initComponents();
        this.dashboard = dashboard;
        this.panelPembayaran = panelPembayaran;
        
        kosongkanForm();
        tampilkanData();
    }
    
    public panelTampilPasien(dashboard3 dashboard ) {
        initComponents();
        this.dashboard = dashboard;
        kosongkanForm();
        tampilkanData();
    }
    
    private void kosongkanForm() {
        txtIdPasien.setText("");
        txtIdPasien.setText("");
        txtNamaPasien.setText("");
        buttonGroup1.clearSelection();
        txtNoHp.setText("");
        txtAlamat.setText("");
        txtCari.setText("");
        txtIdPasien.requestFocus();
    }
    
    private void tampilkanData() {
        Object[] Baris = {"ID Pasien", "Nama Pasien", "Jenis Kelamin", "No HP", "Alamat"};
        tabmode = new DefaultTableModel(null, Baris);
        
        // Pengecekan kalau txtCari belum dibuat, dikasih string kosong aja
        String cariitem = ""; 
        if (txtCari != null) {
            cariitem = txtCari.getText();
        }

        try {
            String sql = "SELECT * FROM pasien WHERE id_pasien LIKE '%" + cariitem + "%' "
                    + "OR nama_pasien LIKE '%" + cariitem + "%'";
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()) {
                tabmode.addRow(new Object[]{
                    hasil.getString("id_pasien"),
                    hasil.getString("nama_pasien"),
                    hasil.getString("jenis_kelamin"),
                    hasil.getString("no_hp"),
                    hasil.getString("alamat")
                });
            }
            tabelPasien.setModel(tabmode);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data gagal dipanggil: " + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIdPasien = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNamaPasien = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        rbLaki = new javax.swing.JRadioButton();
        rbPerempuan = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        txtNoHp = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        btnSimpan = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        txtCari = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelPasien = new javax.swing.JTable();
        btncetak = new javax.swing.JButton();

        setBackground(new java.awt.Color(244, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel1.setText("Data Pasien");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel2.setText("ID Pasien");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        txtIdPasien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(txtIdPasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 130, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel3.setText("Nama Pasien");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        txtNamaPasien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNamaPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaPasienActionPerformed(evt);
            }
        });
        add(txtNamaPasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 130, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel4.setText("Jenis Kelamin");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        buttonGroup1.add(rbLaki);
        rbLaki.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        rbLaki.setText("Laki - Laki");
        rbLaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbLakiActionPerformed(evt);
            }
        });
        add(rbLaki, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, -1));

        buttonGroup1.add(rbPerempuan);
        rbPerempuan.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        rbPerempuan.setText("Perempuan");
        add(rbPerempuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel5.setText("No.HP");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        txtNoHp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNoHp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoHpActionPerformed(evt);
            }
        });
        add(txtNoHp, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 130, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel6.setText("Alamat");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        txtAlamat.setColumns(20);
        txtAlamat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtAlamat.setRows(5);
        jScrollPane1.setViewportView(txtAlamat);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, -1, -1));

        btnSimpan.setBackground(new java.awt.Color(0, 204, 0));
        btnSimpan.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("Simpan");
        btnSimpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, 30));

        btnEdit.setBackground(new java.awt.Color(0, 204, 0));
        btnEdit.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Edit");
        btnEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, -1, 30));

        btnHapus.setBackground(new java.awt.Color(255, 51, 51));
        btnHapus.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("Hapus");
        btnHapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, -1, 30));

        btnBatal.setBackground(new java.awt.Color(0, 204, 0));
        btnBatal.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnBatal.setForeground(new java.awt.Color(255, 255, 255));
        btnBatal.setText("Batal");
        btnBatal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, -1, 30));

        txtCari.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCariKeyPressed(evt);
            }
        });
        add(txtCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, 160, -1));

        jButton1.setBackground(new java.awt.Color(0, 204, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cari");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, -1, -1));

        tabelPasien.setBackground(new java.awt.Color(204, 204, 204));
        tabelPasien.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tabelPasien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tabelPasien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Pasien", "Nama Pasien", "Jenis Kelamin", "No. HP", "Alamat"
            }
        ));
        tabelPasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPasienMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabelPasien);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, 510, -1));

        btncetak.setBackground(new java.awt.Color(51, 51, 255));
        btncetak.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btncetak.setForeground(new java.awt.Color(255, 255, 255));
        btncetak.setText("Cetak");
        btncetak.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btncetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncetakActionPerformed(evt);
            }
        });
        add(btncetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 90, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaPasienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaPasienActionPerformed

    private void rbLakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbLakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbLakiActionPerformed

    private void txtNoHpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoHpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoHpActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        String jk = "";
        if (rbLaki.isSelected()) {
            jk = "Laki-laki";
        } else if (rbPerempuan.isSelected()) {
            jk = "Perempuan";
        } else {
            JOptionPane.showMessageDialog(null, "Pilih jenis kelamin dulu!");
            return;
        }

        try {
            String sql = "INSERT INTO pasien (id_pasien, nama_pasien, jenis_kelamin, no_hp, alamat) VALUES (?,?,?,?,?)";
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, txtIdPasien.getText());
            stat.setString(2, txtNamaPasien.getText());
            stat.setString(3, jk);
            stat.setString(4, txtNoHp.getText());
            stat.setString(5, txtAlamat.getText());

            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil disimpan");
            kosongkanForm();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Gagal disimpan: " + e);
        }
        tampilkanData();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        String jk = "";
        if (rbLaki.isSelected()) {
            jk = "Laki-laki";
        } else if (rbPerempuan.isSelected()) {
            jk = "Perempuan";
        } else {
            JOptionPane.showMessageDialog(null, "Pilih jenis kelamin dulu!");
            return;
        }

        try {
            String sql = "UPDATE pasien SET nama_pasien=?, jenis_kelamin=?, no_hp=?, alamat=? WHERE id_pasien=?";
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, txtNamaPasien.getText());
            stat.setString(2, jk);
            stat.setString(3, txtNoHp.getText());
            stat.setString(4, txtAlamat.getText());
            stat.setString(5, txtIdPasien.getText());

            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil diubah");
            kosongkanForm();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Gagal diubah: " + e);
        }
        tampilkanData();
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        int ok = JOptionPane.showConfirmDialog(null, "Yakin mau hapus data ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (ok == 0) {
            try {
                String sql = "DELETE FROM pasien WHERE id_pasien = ?";
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.setString(1, txtIdPasien.getText());

                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Berhasil dihapus");
                kosongkanForm();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Data Gagal dihapus: " + e);
            }
            tampilkanData();
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        kosongkanForm();
        tampilkanData();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void txtCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            tampilkanData();
        }
    }//GEN-LAST:event_txtCariKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        tampilkanData();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tabelPasienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPasienMouseClicked
        int baris = tabelPasien.getSelectedRow();

    if(baris==-1){
        return;
    }

    String id = tabmode.getValueAt(baris,0).toString();
    String nama = tabmode.getValueAt(baris,1).toString();

    if(panelPembayaran!=null){

        panelPembayaran.setPasienData(id,nama);

        dashboard.showPanel(panelPembayaran);

        return;

    }

    txtIdPasien.setText(id);
    txtNamaPasien.setText(nama);

    String jk = tabmode.getValueAt(baris,2).toString();

    if(jk.equals("Laki-laki")){
        rbLaki.setSelected(true);
    }else{
        rbPerempuan.setSelected(true);
    }

    txtNoHp.setText(tabmode.getValueAt(baris,3).toString());
    txtAlamat.setText(tabmode.getValueAt(baris,4).toString());
    }//GEN-LAST:event_tabelPasienMouseClicked

    private void btncetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncetakActionPerformed
        try {
            // 1. Dapatkan koneksi
            Connection conn = new Koneksi().connect();

            // 2. Tentukan lokasi file .jrxml (Pastikan path ini benar di project Anda)
            String path = "/ireport/pasien.jrxml";
            InputStream reportStream = getClass().getResourceAsStream(path);

            if (reportStream != null) {
                // 3. Kompilasi laporan secara dinamis agar tidak error "InputStream"
                net.sf.jasperreports.engine.JasperReport jr =
                net.sf.jasperreports.engine.JasperCompileManager.compileReport(reportStream);

                // 4. Isi laporan dengan data dari database
                JasperPrint jp = JasperFillManager.fillReport(jr, new HashMap<>(), conn);

                // 5. Tampilkan laporan
                JasperViewer.viewReport(jp, false);
            } else {
                JOptionPane.showMessageDialog(null, "File laporan tidak ditemukan di: " + path);
            }
        } catch (Exception e) {
            // Menampilkan pesan error yang lebih detail di console untuk mempermudah debugging
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Gagal Cetak: " + e.getMessage());
        }
    }//GEN-LAST:event_btncetakActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btncetak;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton rbLaki;
    private javax.swing.JRadioButton rbPerempuan;
    private javax.swing.JTable tabelPasien;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtIdPasien;
    private javax.swing.JTextField txtNamaPasien;
    private javax.swing.JTextField txtNoHp;
    // End of variables declaration//GEN-END:variables
}
