/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tampilan;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import koneksi.Koneksi;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aldi
 */
public class panelTambahPemeriksaan extends javax.swing.JPanel {
    private dashboard3 dashboard;
    Connection conn = new Koneksi().connect();
    PreparedStatement pst;
    ResultSet rs;
    private boolean loadingPasien = false;
    private boolean modeEdit = false;
    private boolean loadingData = false;
    /**
     * Creates new form panelTambahPemeriksaan
     */
    public panelTambahPemeriksaan(dashboard3 dashboard) {
        initComponents();
        this.dashboard = dashboard;
        
        txtNamaPasien.setEditable(false);
        tampilPasien();
        tampilDokter();
        modeEdit = false;
    }
    
    public panelTambahPemeriksaan(dashboard3 dashboard,String idPeriksa){
        initComponents();
        this.dashboard = dashboard;
        txtNamaPasien.setEditable(false);
        tampilPasien();
        tampilDokter();
        modeEdit = true;
        tampilDataEdit(idPeriksa);
        txtNoPeriksa.setEditable(false);

}
    
    private void tampilPasien() {
         loadingPasien = true;

        try {

            cmbPasien.removeAllItems();

            String sql = "SELECT id_pasien FROM pasien";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();

            while(rs.next()){
                cmbPasien.addItem(rs.getString("id_pasien"));
            }

        } catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e.getMessage());

        }

        loadingPasien = false;
}
    
    private void tampilDokter(){
        try{
        cmbDokter.removeAllItems();
        
        String sql="SELECT nama_dokter FROM dokter ORDER BY nama_dokter";
        pst=conn.prepareStatement(sql);
        rs=pst.executeQuery();
        while(rs.next()){
            cmbDokter.addItem(rs.getString("nama_dokter"));

        }

    }catch(Exception e){
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, e.getMessage());

    }

}
    
    private String getIdDokter(String namaDokter){
     String id="";
        try{
            String sql="SELECT id_dokter FROM dokter WHERE nama_dokter=?";
            pst=conn.prepareStatement(sql);
            pst.setString(1,namaDokter);
            rs=pst.executeQuery();
            if(rs.next()){
                id=rs.getString("id_dokter");
            }
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        return id;

}
    
     private void tampilDataEdit(String id){

    try{
        String sql =
        "SELECT periksa.id_periksa, periksa.id_pasien, periksa.id_dokter, " +
        "periksa.tgl_periksa, periksa.diagnosa, periksa.tindakan, " +
        "pasien.nama_pasien, dokter.nama_dokter " +
        "FROM periksa " +
        "JOIN pasien ON pasien.id_pasien = periksa.id_pasien " +
        "JOIN dokter ON dokter.id_dokter = periksa.id_dokter " +
        "WHERE periksa.id_periksa=?";

        PreparedStatement pstLocal = conn.prepareStatement(sql);
        pstLocal.setString(1, id);

        ResultSet rsLocal = pstLocal.executeQuery();

        if(rsLocal.next()){

            txtNoPeriksa.setText(rsLocal.getString("id_periksa"));
            cmbPasien.setSelectedItem(rsLocal.getString("id_pasien"));
            txtNamaPasien.setText(rsLocal.getString("nama_pasien"));
            cmbDokter.setSelectedItem(rsLocal.getString("nama_dokter"));
            txtTanggal.setValue(rsLocal.getDate("tgl_periksa"));
            txtDiagnosis.setText(rsLocal.getString("diagnosa"));
            txtTindakan.setText(rsLocal.getString("tindakan"));
        }

        rsLocal.close();
        pstLocal.close();

    }catch(Exception e){
    e.printStackTrace();
    JOptionPane.showMessageDialog(null, e.getMessage());

    }

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNoPeriksa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmbPasien = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cmbDokter = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTindakan = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        txtTanggal = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        txtNamaPasien = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDiagnosis = new javax.swing.JTextArea();
        btnSimpan1 = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(244, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 28)); // NOI18N
        jLabel1.setText("Form Tambah Pemeriksaan Baru");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 420, 36));

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel4.setText("No Pemeriksaan");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 122, -1, 36));
        jPanel1.add(txtNoPeriksa, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 164, 304, 35));

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel5.setText("No Pasien");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 217, -1, 36));

        cmbPasien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPasienActionPerformed(evt);
            }
        });
        jPanel1.add(cmbPasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 259, 304, 35));

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel3.setText("Nama Dokter");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 312, -1, 36));

        cmbDokter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dokter A", "Dokter B", "Dokter C", "Dokter D" }));
        cmbDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDokterActionPerformed(evt);
            }
        });
        jPanel1.add(cmbDokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 354, 304, 36));

        jLabel6.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel6.setText("Tindakan Lanjut");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 408, -1, 36));

        txtTindakan.setColumns(20);
        txtTindakan.setRows(5);
        jScrollPane1.setViewportView(txtTindakan);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 450, 737, -1));

        jLabel7.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel7.setText("Tanggal Pemeriksaan");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(487, 122, 503, 36));

        txtTanggal.setModel(new javax.swing.SpinnerDateModel());
        jPanel1.add(txtTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(487, 164, 277, 35));

        jLabel8.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel8.setText("Nama Pasien");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(487, 217, -1, 36));

        txtNamaPasien.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtNamaPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaPasienActionPerformed(evt);
            }
        });
        jPanel1.add(txtNamaPasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(487, 259, 277, 35));

        jLabel9.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel9.setText("Diagnosis Awal");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(487, 312, -1, 36));

        txtDiagnosis.setColumns(20);
        txtDiagnosis.setRows(5);
        jScrollPane2.setViewportView(txtDiagnosis);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(487, 354, 277, -1));

        btnSimpan1.setBackground(new java.awt.Color(0, 153, 0));
        btnSimpan1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnSimpan1.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan1.setText("Simpan Data");
        btnSimpan1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSimpan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpan1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnSimpan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 572, 137, 36));

        btnBatal.setBackground(new java.awt.Color(0, 153, 0));
        btnBatal.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnBatal.setForeground(new java.awt.Color(255, 255, 255));
        btnBatal.setText("Batal");
        btnBatal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        jPanel1.add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 572, 98, 36));

        btnKeluar.setBackground(new java.awt.Color(0, 153, 0));
        btnKeluar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnKeluar.setForeground(new java.awt.Color(255, 255, 255));
        btnKeluar.setText("Kembali");
        btnKeluar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        jPanel1.add(btnKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(666, 572, 98, 36));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 950));
    }// </editor-fold>//GEN-END:initComponents

    private void cmbPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPasienActionPerformed
        if (loadingPasien) {
        return;
    }
        
        try{
            String sql="SELECT nama_pasien FROM pasien WHERE id_pasien=?";
            pst=conn.prepareStatement(sql);
            if (cmbPasien.getSelectedItem() == null) {
                return;
            }
            pst.setString(1,cmbPasien.getSelectedItem().toString());
            rs=pst.executeQuery();
            if(rs.next()){
                txtNamaPasien.setText(rs.getString("nama_pasien"));
            }
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_cmbPasienActionPerformed

    private void cmbDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDokterActionPerformed
       
    }//GEN-LAST:event_cmbDokterActionPerformed

    private void txtNamaPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaPasienActionPerformed

    }//GEN-LAST:event_txtNamaPasienActionPerformed

    private void btnSimpan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpan1ActionPerformed
       if (txtNoPeriksa.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this,
                "No Pemeriksaan harus diisi!",
                "Peringatan",
                JOptionPane.WARNING_MESSAGE);
        txtNoPeriksa.requestFocus();
        return;
    }
        
        try {

            // cek apakah id_periksa sudah ada
            String cek = "SELECT * FROM periksa WHERE id_periksa=?";
            pst = conn.prepareStatement(cek);
            pst.setString(1, txtNoPeriksa.getText().trim());

            rs = pst.executeQuery();

            java.util.Date tgl = (java.util.Date) txtTanggal.getValue();
            java.sql.Date tanggal = new java.sql.Date(tgl.getTime());

            String idDokter = getIdDokter(cmbDokter.getSelectedItem().toString());

            if(modeEdit){

                // ================= UPDATE =================
                String sql = "UPDATE periksa SET "
                + "id_dokter=?,"
                + "id_pasien=?,"
                + "tgl_periksa=?,"
                + "diagnosa=?,"
                + "tindakan=? "
                + "WHERE id_periksa=?";

                pst = conn.prepareStatement(sql);

                pst.setString(1, idDokter);
                pst.setString(2, cmbPasien.getSelectedItem().toString());
                pst.setDate(3, tanggal);
                pst.setString(4, txtDiagnosis.getText());
                pst.setString(5, txtTindakan.getText());
                pst.setString(6, txtNoPeriksa.getText().trim());

                pst.executeUpdate();

                JOptionPane.showMessageDialog(null, "Data berhasil diupdate");

            }else{

                // ================= INSERT =================
                String sql = "INSERT INTO periksa VALUES (?,?,?,?,?,?)";

                pst = conn.prepareStatement(sql);

                pst.setString(1, txtNoPeriksa.getText());
                pst.setString(2, idDokter);
                pst.setString(3, cmbPasien.getSelectedItem().toString());
                pst.setDate(4, tanggal);
                pst.setString(5, txtDiagnosis.getText());
                pst.setString(6, txtTindakan.getText());

                pst.executeUpdate();

                JOptionPane.showMessageDialog(null, "Data berhasil disimpan");

            }

            dashboard.showPanel(new panelTampilPemeriksaan(dashboard));

        } catch(Exception e){
    e.printStackTrace();
    JOptionPane.showMessageDialog(null, e.getMessage());

        }
    }//GEN-LAST:event_btnSimpan1ActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed

        txtNoPeriksa.setText("");
        txtNamaPasien.setText("");
        txtDiagnosis.setText("");
        txtTindakan.setText("");

        if(cmbPasien.getItemCount()>0)
        cmbPasien.setSelectedIndex(0);

        if(cmbDokter.getItemCount()>0)
        cmbDokter.setSelectedIndex(0);
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed

        dashboard.showPanel(new panelTampilPemeriksaan(dashboard));
    }//GEN-LAST:event_btnKeluarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnSimpan1;
    private javax.swing.JComboBox<String> cmbDokter;
    private javax.swing.JComboBox<String> cmbPasien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtDiagnosis;
    private javax.swing.JTextField txtNamaPasien;
    private javax.swing.JTextField txtNoPeriksa;
    private javax.swing.JSpinner txtTanggal;
    private javax.swing.JTextArea txtTindakan;
    // End of variables declaration//GEN-END:variables
}
