/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tampilan;

/**
 *
 * @author Aldi
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.Koneksi;

import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
public class panelTampilPendaftaran extends javax.swing.JPanel {
     private dashboard3 dashboard;
     private Connection conn = new Koneksi().connect();
     PreparedStatement pst;
     ResultSet rs;
     private String idTerpilih = ""; 
     private String poliTerpilih = "";  
     private String statusTerpilih = ""; 
    /**
     * Creates new form panelTampilPendaftaran
     */
    public panelTampilPendaftaran(dashboard3 dashboard) {
        initComponents();
        this.dashboard = dashboard;
        initKoneksi();
        loadDataTabel();
    }
    
    private void initKoneksi() {
    conn = new Koneksi().connect();

    if (conn == null) {
        JOptionPane.showMessageDialog(this,
                "Gagal koneksi ke database!");
    }
}
    
       public void loadDataTabel() {

    try {

        // cek koneksi
        if (conn == null || conn.isClosed()) {
            conn = new Koneksi().connect();
        }

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        String sql = "SELECT no_pendaftaran, tanggal, nama_pasien, poli, status "
                   + "FROM pendaftaran ORDER BY no_pendaftaran ASC";

        PreparedStatement pst = conn.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();

        while (rs.next()) {

            String dbPoli = rs.getString("poli");
            String visualPoli = dbPoli;

            if(dbPoli.equals("poli_umum")){
                visualPoli = "Poli Umum";
            }else if(dbPoli.equals("poli_gigi")){
                visualPoli = "Poli Gigi";
            }else if(dbPoli.equals("poli_tht")){
                visualPoli = "Poli THT";
            }else if(dbPoli.equals("poli_mata")){
                visualPoli = "Poli Mata";
            }else if(dbPoli.equals("poli_spesialis")){
                visualPoli = "Poli Spesialis";
            }else if(dbPoli.equals("poli_anak")){
                visualPoli = "Poli Anak";
            }

            String dbStatus = rs.getString("status");
            String visualStatus = dbStatus.substring(0,1).toUpperCase()
                    + dbStatus.substring(1).toLowerCase();

            model.addRow(new Object[]{
                rs.getString("no_pendaftaran"),
                rs.getTimestamp("tanggal"),
                rs.getString("nama_pasien"),
                visualPoli,
                visualStatus
            });

        }

    } catch (SQLException ex) {

        JOptionPane.showMessageDialog(null,
                "Gagal memuat data : " + ex.getMessage());

    }
}
       
       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btambah = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        bedit = new javax.swing.JButton();
        bhapus = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        bPilihData = new javax.swing.JButton();
        btnCetak = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(244, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 28)); // NOI18N
        jLabel1.setText("Pendaftaran");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        btambah.setBackground(new java.awt.Color(0, 153, 51));
        btambah.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btambah.setForeground(new java.awt.Color(255, 255, 255));
        btambah.setText("Tambah Pendaftaran Baru");
        btambah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btambahActionPerformed(evt);
            }
        });
        jPanel1.add(btambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 210, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No Pendaftaran", "Tgl Daftar", "Nama Pasien", "Poli", "Status"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 710, -1));

        bedit.setBackground(new java.awt.Color(0, 153, 51));
        bedit.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        bedit.setForeground(new java.awt.Color(255, 255, 255));
        bedit.setText("Edit");
        bedit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beditActionPerformed(evt);
            }
        });
        jPanel1.add(bedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, -1, 30));

        bhapus.setBackground(new java.awt.Color(255, 51, 51));
        bhapus.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        bhapus.setForeground(new java.awt.Color(255, 255, 255));
        bhapus.setText("Hapus");
        bhapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhapusActionPerformed(evt);
            }
        });
        jPanel1.add(bhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, -1, 31));

        jButton4.setText("Cetak");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 120, -1, 30));

        bPilihData.setBackground(new java.awt.Color(0, 153, 51));
        bPilihData.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        bPilihData.setForeground(new java.awt.Color(255, 255, 255));
        bPilihData.setText("Pilih Data");
        bPilihData.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bPilihData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bPilihDataMouseClicked(evt);
            }
        });
        bPilihData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPilihDataActionPerformed(evt);
            }
        });
        jPanel1.add(bPilihData, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 113, 30));

        btnCetak.setBackground(new java.awt.Color(51, 102, 255));
        btnCetak.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnCetak.setForeground(new java.awt.Color(255, 255, 255));
        btnCetak.setText("Cetak");
        btnCetak.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });
        jPanel1.add(btnCetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 70, -1, 30));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 950));
    }// </editor-fold>//GEN-END:initComponents

    private void btambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btambahActionPerformed
        dashboard.showPanel(new panelTambahPendaftaran(dashboard));
    }//GEN-LAST:event_btambahActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int baris = jTable1.getSelectedRow();
        if (baris != -1) {
            idTerpilih = jTable1.getValueAt(baris, 0) != null ? jTable1.getValueAt(baris, 0).toString() : "";
            poliTerpilih = jTable1.getValueAt(baris, 3) != null ? jTable1.getValueAt(baris, 3).toString() : "";
            statusTerpilih = jTable1.getValueAt(baris, 4) != null ? jTable1.getValueAt(baris, 4).toString() : "";
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void beditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beditActionPerformed
         int baris = jTable1.getSelectedRow();

    if (baris == -1) {
        JOptionPane.showMessageDialog(this,
                "Silakan pilih data terlebih dahulu!");
        return;
    }

    String id = jTable1.getValueAt(baris, 0).toString();

    java.util.Date tanggal =
            (java.util.Date) jTable1.getValueAt(baris, 1);

    String nama = jTable1.getValueAt(baris, 2).toString();

    String poli = jTable1.getValueAt(baris, 3).toString();

    String status = jTable1.getValueAt(baris, 4).toString();

    dashboard.showPanel(new panelEditPendaftaran(
            dashboard,
            id,
            nama,
            tanggal,
            poli,
            status));
    }//GEN-LAST:event_beditActionPerformed

    private void bhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapusActionPerformed
        if(idTerpilih.equals("")){

        JOptionPane.showMessageDialog(null,
                "Pilih data terlebih dahulu!");

        return;
    }

    int jawab = JOptionPane.showConfirmDialog(
            null,
            "Hapus data ini?",
            "Konfirmasi",
            JOptionPane.YES_NO_OPTION);

    if(jawab==JOptionPane.YES_OPTION){

        try{

            if(conn==null || conn.isClosed()){
                conn = new Koneksi().connect();
            }

            String sql =
                    "DELETE FROM pendaftaran "
                    + "WHERE no_pendaftaran=?";

            pst = conn.prepareStatement(sql);

            pst.setString(1,idTerpilih);

            pst.executeUpdate();

            JOptionPane.showMessageDialog(null,
                    "Data berhasil dihapus");

            loadDataTabel();

            idTerpilih="";
            poliTerpilih="";
            statusTerpilih="";

        }catch(Exception e){

            JOptionPane.showMessageDialog(null,e);

        }
    }
    }//GEN-LAST:event_bhapusActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       
    }//GEN-LAST:event_jButton4ActionPerformed

    private void bPilihDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bPilihDataMouseClicked
       
    }//GEN-LAST:event_bPilihDataMouseClicked

    private void bPilihDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPilihDataActionPerformed
         beditActionPerformed(evt);
    }//GEN-LAST:event_bPilihDataActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        try{

        if(conn==null || conn.isClosed()){
            conn = new Koneksi().connect();
        }

        JasperReport jr =
                JasperCompileManager.compileReport(
                getClass().getResourceAsStream(
                "/ireport/laporanpendaftaran.jrxml"));

        Map<String,Object> param =
                new HashMap<>();

        JasperPrint jp =
                JasperFillManager.fillReport(
                        jr,
                        param,
                        conn);

        JasperViewer.viewReport(jp,false);

    }catch(Exception e){

        e.printStackTrace();

        JOptionPane.showMessageDialog(null,
                e.getMessage());

    }
    }//GEN-LAST:event_btnCetakActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bPilihData;
    private javax.swing.JButton bedit;
    private javax.swing.JButton bhapus;
    private javax.swing.JButton btambah;
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
