/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tampilan;

/**
 *
 * @author Aldi
 */
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.event.KeyEvent;
import java.util.HashMap;
import java.util.Map;
import koneksi.Koneksi;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

public class panelTampilDokter extends javax.swing.JPanel {
private dashboard3 dashboard;
private Connection conn = new Koneksi().connect();
private DefaultTableModel tabmode;
    /**
     * Creates new form panelTampilDokter
     */
    public panelTampilDokter(dashboard3 dashboard) {
        initComponents();
        this.dashboard = dashboard;
         datatable();
    }
    
    protected void datatable(){
        
        Object[] Baris = {"ID Dokter","Nama Dokter","No.Telepon","Spesialis","Alamat","Jenis"};
        tabmode = new DefaultTableModel(null, Baris);
        
        String nama = tnmdokter.getText().trim();
        String spesialis = cbspesialis.getSelectedItem().toString();
        
        String sql = "SELECT * FROM dokter WHERE 1=1";
        if(!nama.equals("")){
            sql += " AND nama_dokter LIKE '%"+nama+"%'";
        }
        
        if(!spesialis.equals("Semua Spesialis")){
            sql += " AND spesialis='"+spesialis+"'";
        }
        
        sql += " ORDER BY id_dokter ASC";

        try{
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            
            while(hasil.next()){
                tabmode.addRow(new Object[]{
                    hasil.getString("id_dokter"),
                    hasil.getString("nama_dokter"),
                    hasil.getString("no_hp"),
                    hasil.getString("spesialis"),
                    hasil.getString("alamat"),
                    hasil.getString("jenis_kelamin")
                });
            }
            
            tabeldokter.setModel(tabmode);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tnmdokter = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbspesialis = new javax.swing.JComboBox<>();
        btambah = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabeldokter = new javax.swing.JTable();
        bcari = new javax.swing.JButton();
        bcetak = new javax.swing.JButton();
        bubah = new javax.swing.JButton();
        bhapus = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(244, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1366, 768));
        jPanel1.setMinimumSize(new java.awt.Dimension(1366, 768));
        jPanel1.setPreferredSize(new java.awt.Dimension(1290, 930));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 28)); // NOI18N
        jLabel1.setText("Data Dokter");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel2.setText("Nama Dokter");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 98, -1));

        tnmdokter.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tnmdokter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tnmdokterKeyPressed(evt);
            }
        });
        jPanel1.add(tnmdokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 141, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel3.setText("Spesialis");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 83, -1));

        cbspesialis.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbspesialis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semua Spesialis", "Spesialis Anak", "Spesialis Bedah", "Spesialis Penyakit Dalam", "Spesialis Kandungan", "Spesialis Gigi", "Spesialis Mata", "Spesialis THT", "Spesialis Kulit dan Kelamin", "Spesialis Jantung", "Spesialis Saraf", " " }));
        cbspesialis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(cbspesialis, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 150, -1));

        btambah.setBackground(new java.awt.Color(0, 153, 0));
        btambah.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btambah.setForeground(new java.awt.Color(255, 255, 255));
        btambah.setText("Tambah Data Dokter");
        btambah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btambahActionPerformed(evt);
            }
        });
        jPanel1.add(btambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        tabeldokter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Kd Dokter", "Nama Dokter", "Spesialis", "Jk", "No. Telp", "Alamat"
            }
        ));
        jScrollPane1.setViewportView(tabeldokter);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 689, 263));

        bcari.setBackground(new java.awt.Color(0, 153, 0));
        bcari.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        bcari.setForeground(new java.awt.Color(255, 255, 255));
        bcari.setText("Terapkan Filter");
        bcari.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcariActionPerformed(evt);
            }
        });
        jPanel1.add(bcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, -1, -1));

        bcetak.setBackground(new java.awt.Color(0, 102, 255));
        bcetak.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        bcetak.setForeground(new java.awt.Color(255, 255, 255));
        bcetak.setText("Cetak");
        bcetak.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bcetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcetakActionPerformed(evt);
            }
        });
        jPanel1.add(bcetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 110, -1, -1));

        bubah.setBackground(new java.awt.Color(0, 153, 0));
        bubah.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        bubah.setForeground(new java.awt.Color(255, 255, 255));
        bubah.setText("Ubah");
        bubah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bubahActionPerformed(evt);
            }
        });
        jPanel1.add(bubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 430, -1, -1));

        bhapus.setBackground(new java.awt.Color(255, 51, 51));
        bhapus.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        bhapus.setForeground(new java.awt.Color(255, 255, 255));
        bhapus.setText("Hapus");
        bhapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhapusActionPerformed(evt);
            }
        });
        jPanel1.add(bhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 430, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1330, 960));
    }// </editor-fold>//GEN-END:initComponents

    private void tnmdokterKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tnmdokterKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            datatable();
        }
    }//GEN-LAST:event_tnmdokterKeyPressed

    private void btambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btambahActionPerformed
        dashboard.showPanel(new panelTambahDokter(dashboard));
    }//GEN-LAST:event_btambahActionPerformed

    private void bcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcariActionPerformed
        
        datatable();
    }//GEN-LAST:event_bcariActionPerformed

    private void bubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bubahActionPerformed
        // TODO add your handling code here:
        int baris = tabeldokter.getSelectedRow();

        if(baris == -1){
            JOptionPane.showMessageDialog(null,"Pilih data yang akan diubah!");
            return;
        }

        panelEditDokter panel = new panelEditDokter(dashboard);
        panel.setData(
            tabmode.getValueAt(baris,0).toString(),
            tabmode.getValueAt(baris,1).toString(),
            tabmode.getValueAt(baris,2).toString(),
            tabmode.getValueAt(baris,3).toString(),
            tabmode.getValueAt(baris,4).toString(),
            tabmode.getValueAt(baris,5).toString()
        );

        dashboard.showPanel(panel);
    }//GEN-LAST:event_bubahActionPerformed

    private void bhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapusActionPerformed
        // TODO add your handling code here:
        int bar = tabeldokter.getSelectedRow();
        if (bar == -1) {
            JOptionPane.showMessageDialog(null, "pilih data dokter yang ingin dihapus");
            return;
        }
        String id = tabmode.getValueAt(bar, 0).toString();
        int ok = JOptionPane.showConfirmDialog(null, "hapus data dokter " + id + " ?", "konfirmasi dialog",
            JOptionPane.YES_NO_OPTION);
        if (ok == 0) {
            String sql = "delete from dokter where id_dokter = ?";
            try {
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.setString(1, id);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "data berhasil dihapus");
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "data gagal dihapus" + e);
            }
            datatable();
        }
    }//GEN-LAST:event_bhapusActionPerformed

    private void bcetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcetakActionPerformed
        try {

            if (conn == null || conn.isClosed()) {
                conn = new Koneksi().connect();
            }

            JasperReport jr = JasperCompileManager.compileReport(
                getClass().getResourceAsStream("/ireport/dokter.jrxml")
            );

            Map<String, Object> param = new HashMap<>();
            JasperPrint jp = JasperFillManager.fillReport(jr, param, conn);
            JasperViewer.viewReport(jp, false);

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Gagal mencetak laporan: " + e.getMessage());
        }
    }//GEN-LAST:event_bcetakActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bcari;
    private javax.swing.JButton bcetak;
    private javax.swing.JButton bhapus;
    private javax.swing.JButton btambah;
    private javax.swing.JButton bubah;
    private javax.swing.JComboBox<String> cbspesialis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabeldokter;
    private javax.swing.JTextField tnmdokter;
    // End of variables declaration//GEN-END:variables
}
