/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tampilan;

/**
 *
 * @author Aldi
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import javax.swing.table.DefaultTableModel;
import koneksi.Koneksi;
import java.io.InputStream;

import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

public class panelTampilPembayaran extends javax.swing.JPanel {
    private dashboard3 dashboard;
    Connection conn = new Koneksi().connect();
    PreparedStatement pst;
    ResultSet rs;
    private String idPayment = "";
    /**
     * Creates new form panelTampilPembayaran
     */
    public panelTampilPembayaran(dashboard3 dashboard) {
        initComponents();
        this.dashboard = dashboard;
        initTanggalSekarang();
        loadDataBayar();
    }
    
     // Set jSpinner1 ke tanggal dan waktu sekarang secara otomatis
    private void initTanggalSekarang() {
        jSpinner1.setModel(new SpinnerDateModel());
        JSpinner.DateEditor dateEditor = new JSpinner.DateEditor(jSpinner1, "yyyy-MM-dd HH:mm:ss");
        jSpinner1.setEditor(dateEditor);
        jSpinner1.setValue(new Date()); 
    }
    
    private void loadDataBayar() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID Pembayaran");
    model.addColumn("ID Pasien");
    model.addColumn("Nama Pasien");
    model.addColumn("Metode Pembayaran");
    model.addColumn("Jumlah Bayar");
    model.addColumn("Tanggal Pembayaran");

    try {
        String sql = "SELECT "
                + "p.id_payment, "
                + "p.id_pasien, "
                + "ps.nama_pasien, "
                + "p.metode_pembayaran, "
                + "p.jumlah_bayar, "
                + "p.tanggal_pembayaran "
                + "FROM payment p "
                + "JOIN pasien ps ON p.id_pasien = ps.id_pasien "
                + "ORDER BY p.id_payment ASC";

        pst = conn.prepareStatement(sql);
        rs = pst.executeQuery();

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("id_payment"),
                rs.getString("id_pasien"),
                rs.getString("nama_pasien"),
                rs.getString("metode_pembayaran"),
                rs.getDouble("jumlah_bayar"),
                rs.getTimestamp("tanggal_pembayaran")
            });
        }

        tblPembayaran.setModel(model);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
}
    
    public void setPasienData(String kdPasien, String namaPasien) {
        txtidpasien.setText(kdPasien);
        txtnmpasien.setText(namaPasien);
    }
    
    private void clearForm(){

    txtidpasien.setText("");
    txtnmpasien.setText("");
    txtmtdbayar.setSelectedIndex(0);
    txtjmlbayar.setEditable(true);   // tambahkan
    txtjmlbayar.setText("");
    jSpinner1.setValue(new java.util.Date());
    tblPembayaran.clearSelection();
    idPayment = "";
}
    
    private void cekMetodeBayar(){

    String metode = txtmtdbayar.getSelectedItem().toString();

    if(metode.equals("BPJS")){
        txtjmlbayar.setText("0");
        txtjmlbayar.setEditable(false);
    }else{
        txtjmlbayar.setText("");
        txtjmlbayar.setEditable(true);
    }

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtidpasien = new javax.swing.JTextField();
        bcari = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtnmpasien = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPembayaran = new javax.swing.JTable();
        bbatal = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();
        txtmtdbayar = new javax.swing.JComboBox<>();
        txtjmlbayar = new javax.swing.JTextField();
        bsimpan = new javax.swing.JButton();
        bhapus = new javax.swing.JButton();
        bcetak = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1290, 950));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(244, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1366, 768));
        jPanel1.setMinimumSize(new java.awt.Dimension(1366, 768));
        jPanel1.setPreferredSize(new java.awt.Dimension(1290, 950));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Pembayaran Pasien");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel2.setText("id Pasien");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 103, -1, -1));
        jPanel1.add(txtidpasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 129, 150, 34));

        bcari.setBackground(new java.awt.Color(0, 153, 51));
        bcari.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        bcari.setForeground(new java.awt.Color(255, 255, 255));
        bcari.setText("Cari");
        bcari.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcariActionPerformed(evt);
            }
        });
        jPanel1.add(bcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 129, -1, 34));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel3.setText("Nama Pasien");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 245, -1, -1));
        jPanel1.add(txtnmpasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 271, 150, 34));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel4.setText("Metode Pembayaran");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 111, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel5.setText("Jumlah Bayar");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 167, -1, -1));

        tblPembayaran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id Pembayaran", "Id Pasien", "Nama Pasien", "Metode Pembayaran", "Jumlah Bayar", "Tanggal Pembayaran"
            }
        ));
        tblPembayaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPembayaranMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPembayaran);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 332, 840, 326));

        bbatal.setBackground(new java.awt.Color(0, 153, 51));
        bbatal.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        bbatal.setForeground(new java.awt.Color(255, 255, 255));
        bbatal.setText("Batal");
        bbatal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbatalActionPerformed(evt);
            }
        });
        jPanel1.add(bbatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, -1, 38));

        jSpinner1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jSpinner1.setModel(new javax.swing.SpinnerDateModel());
        jSpinner1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSpinner1MouseClicked(evt);
            }
        });
        jPanel1.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 271, -1, -1));

        txtmtdbayar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BPJS", "Tunai", "Transfer" }));
        txtmtdbayar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtmtdbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmtdbayarActionPerformed(evt);
            }
        });
        jPanel1.add(txtmtdbayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 103, 243, 38));
        jPanel1.add(txtjmlbayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 159, 243, 38));

        bsimpan.setBackground(new java.awt.Color(0, 153, 51));
        bsimpan.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        bsimpan.setForeground(new java.awt.Color(255, 255, 255));
        bsimpan.setText("Simpan");
        bsimpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsimpanActionPerformed(evt);
            }
        });
        jPanel1.add(bsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, -1, 37));

        bhapus.setBackground(new java.awt.Color(255, 51, 51));
        bhapus.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        bhapus.setForeground(new java.awt.Color(255, 255, 255));
        bhapus.setText("Hapus");
        bhapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhapusActionPerformed(evt);
            }
        });
        jPanel1.add(bhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 270, -1, 34));

        bcetak.setBackground(new java.awt.Color(0, 102, 255));
        bcetak.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        bcetak.setForeground(new java.awt.Color(255, 255, 255));
        bcetak.setText("Cetak");
        bcetak.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bcetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcetakActionPerformed(evt);
            }
        });
        jPanel1.add(bcetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 270, -1, 34));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 950));
    }// </editor-fold>//GEN-END:initComponents

    private void bcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcariActionPerformed
        dashboard.showPanel(new panelTampilPasien(dashboard, this));
    }//GEN-LAST:event_bcariActionPerformed

    private void tblPembayaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPembayaranMouseClicked
        // Sinkronisasi baris jTable1 kembali ke textfield saat diklik
        int baris = tblPembayaran.getSelectedRow();

        if(baris == -1){
            return;
        }

        idPayment = tblPembayaran.getValueAt(baris,0).toString();

        txtidpasien.setText(tblPembayaran.getValueAt(baris,1).toString());
        txtnmpasien.setText(tblPembayaran.getValueAt(baris,2).toString());
        txtmtdbayar.setSelectedItem(tblPembayaran.getValueAt(baris,3).toString());
        txtjmlbayar.setText(tblPembayaran.getValueAt(baris,4).toString());
    }//GEN-LAST:event_tblPembayaranMouseClicked

    private void bbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbatalActionPerformed
        // BATAL / CLEAR AREA TEXTFIELD
        clearForm();
    }//GEN-LAST:event_bbatalActionPerformed

    private void jSpinner1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSpinner1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jSpinner1MouseClicked

    private void txtmtdbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmtdbayarActionPerformed

       cekMetodeBayar();
    }//GEN-LAST:event_txtmtdbayarActionPerformed

    private void bsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpanActionPerformed
        // SIMPAN DATA KE DATABASE
String idPasien = txtidpasien.getText().trim();
String namaPasien = txtnmpasien.getText().trim();
String metode = txtmtdbayar.getSelectedItem().toString();
String jumlah = txtjmlbayar.getText().trim();
Date tanggal = (Date) jSpinner1.getValue();

if (idPasien.equals("") || jumlah.equals("")) {
    JOptionPane.showMessageDialog(null, "Data belum lengkap!");
    return;
}

try {
    String sql = "INSERT INTO payment "
            + "(id_pasien, nama_pasien, metode_pembayaran, jumlah_bayar, tanggal_pembayaran) "
            + "VALUES (?, ?, ?, ?, ?)";

    pst = conn.prepareStatement(sql);

    pst.setString(1, idPasien);
    pst.setString(2, namaPasien);
    pst.setString(3, metode);
    pst.setDouble(4, Double.parseDouble(jumlah));
    pst.setTimestamp(5, new java.sql.Timestamp(tanggal.getTime()));

    pst.executeUpdate();

    JOptionPane.showMessageDialog(null, "Data pembayaran berhasil disimpan");

    loadDataBayar();
    clearForm();

} catch (Exception e) {
    JOptionPane.showMessageDialog(null, e);
}
    }//GEN-LAST:event_bsimpanActionPerformed

    private void bhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapusActionPerformed
        // HAPUS DATA YANG DIPILIH PADA TABEL
       if(idPayment.equals("")){

        JOptionPane.showMessageDialog(null,
                "Pilih data terlebih dahulu!");

        return;
    }

    int jawab = JOptionPane.showConfirmDialog(
            null,
            "Hapus data pembayaran ini?",
            "Konfirmasi",
            JOptionPane.YES_NO_OPTION);

    if(jawab == JOptionPane.YES_OPTION){

        try{

            String sql = "DELETE FROM payment WHERE id_payment=?";

            pst = conn.prepareStatement(sql);

            pst.setString(1, idPayment);

            pst.executeUpdate();

            JOptionPane.showMessageDialog(null,
                    "Data berhasil dihapus");

            loadDataBayar();

            clearForm();

        }catch(Exception e){

            JOptionPane.showMessageDialog(null,e);

        }

    }

    }//GEN-LAST:event_bhapusActionPerformed

    private void bcetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcetakActionPerformed
        // CETAK: Cetak single data terpilih di jTable1 menggunakan iReport
       if(idPayment.equals("")){

        JOptionPane.showMessageDialog(null,
                "Pilih data terlebih dahulu!");

        return;
    }

    try{

        InputStream report = getClass().getResourceAsStream("/ireport/payment.jrxml");

        if(report == null){
            JOptionPane.showMessageDialog(null,
                    "File payment.jrxml tidak ditemukan!");
            return;
        }

        JasperReport jr = JasperCompileManager.compileReport(report);

        Map<String,Object> param = new HashMap<>();

        param.put("id_payment", Integer.parseInt(idPayment));

        JasperPrint jp = JasperFillManager.fillReport(
                jr,
                param,
                conn);

        JasperViewer.viewReport(jp,false);

    }catch (Exception e) {
    e.printStackTrace();

    Throwable t = e;
    while (t != null) {
        System.out.println("CAUSE = " + t);
        t = t.getCause();
    }
    
    }


    }//GEN-LAST:event_bcetakActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bbatal;
    private javax.swing.JButton bcari;
    private javax.swing.JButton bcetak;
    private javax.swing.JButton bhapus;
    private javax.swing.JButton bsimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable tblPembayaran;
    private javax.swing.JTextField txtidpasien;
    private javax.swing.JTextField txtjmlbayar;
    private javax.swing.JComboBox<String> txtmtdbayar;
    private javax.swing.JTextField txtnmpasien;
    // End of variables declaration//GEN-END:variables
}
