/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tampilan;

/**
 *
 * @author Aldi
 */
import java.sql.*;
import javax.swing.JOptionPane;
import koneksi.Koneksi;
public class panelEditRuangan extends javax.swing.JPanel {
private dashboard3 dashboard;
private Connection conn = new Koneksi().connect();
    /**
     * Creates new form panelEditRuangan
     */
    public panelEditRuangan(dashboard3 dashboard) {
        initComponents();
        this.dashboard = dashboard;
    }
    
    public void setRuangan(String kdruangan, String nmruangan, String jenis, String lantai, String kapasitas, String fasilitas, String status) {
        this.kdruangan.setText(kdruangan);
        this.nmruangan.setText(nmruangan);
        this.jenis.setSelectedItem(jenis);
        this.lantai.setValue(Integer.parseInt(lantai));
        this.kapasitas.setValue(Integer.parseInt(kapasitas));
        this.fasilitas.setText(fasilitas);
        if (status.equals("Tersedia")) {
            tersedia.setSelected(true);
        } else if (status.equals("Sedang digunakan")) {
            digunakan.setSelected(true);
        }

        this.kdruangan.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        kdruangan = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nmruangan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jenis = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        bbatal = new javax.swing.JButton();
        bubah = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        lantai = new javax.swing.JSpinner();
        kapasitas = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        fasilitas = new javax.swing.JTextArea();
        tersedia = new javax.swing.JRadioButton();
        digunakan = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(244, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1366, 768));
        jPanel1.setMinimumSize(new java.awt.Dimension(1366, 768));
        jPanel1.setPreferredSize(new java.awt.Dimension(559, 331));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 28)); // NOI18N
        jLabel1.setText("Edit Data Ruangan");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 240, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel2.setText("Kode Ruangan");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 180, -1));

        kdruangan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        kdruangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kdruanganActionPerformed(evt);
            }
        });
        jPanel1.add(kdruangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 180, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel3.setText("Nama Ruangan");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        nmruangan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nmruangan.setName(""); // NOI18N
        jPanel1.add(nmruangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 180, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel4.setText("Jenis Ruangan");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 100, -1));

        jenis.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih Jenis Ruangan--", "Rawat Inap", "Poliklinik", "IGD", "Kritis", "Operasi" }));
        jPanel1.add(jenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 180, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel6.setText("Lantai");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 60, -1));

        bbatal.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        bbatal.setText("Batal");
        bbatal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbatalActionPerformed(evt);
            }
        });
        jPanel1.add(bbatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, 80, -1));

        bubah.setBackground(new java.awt.Color(0, 153, 0));
        bubah.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        bubah.setForeground(new java.awt.Color(255, 255, 255));
        bubah.setText("Ubah");
        bubah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bubahActionPerformed(evt);
            }
        });
        jPanel1.add(bubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 80, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel7.setText("Kapasitas");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 100, -1));

        lantai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lantai.setModel(new javax.swing.SpinnerNumberModel(1, 0, 4, 1));
        jPanel1.add(lantai, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 180, -1));

        kapasitas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        kapasitas.setModel(new javax.swing.SpinnerNumberModel(0, 0, 5, 1));
        jPanel1.add(kapasitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 180, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel5.setText("Fasilitas");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, -1, -1));

        fasilitas.setColumns(20);
        fasilitas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fasilitas.setRows(5);
        jScrollPane1.setViewportView(fasilitas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 180, 149));

        tersedia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tersedia.setText("Tersedia");
        jPanel1.add(tersedia, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, -1, -1));

        digunakan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        digunakan.setText("Sedang digunakan");
        jPanel1.add(digunakan, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel8.setText("Status");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 950));
    }// </editor-fold>//GEN-END:initComponents

    private void kdruanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kdruanganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kdruanganActionPerformed

    private void bbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbatalActionPerformed
        dashboard.showPanel(new panelTampilRuangan(dashboard));
        kdruangan.requestFocus();
    }//GEN-LAST:event_bbatalActionPerformed

    private void bubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bubahActionPerformed
        // TODO add your handling code here:
        String sql = "UPDATE ruangan SET nama_ruangan=?, jenis=?, lantai=?, kapasitas=?, fasilitas=?, status=? WHERE kd_ruangan=?";
        try (PreparedStatement stat = conn.prepareStatement(sql)) {
            stat.setString(1, nmruangan.getText());
            stat.setString(2, (String) jenis.getSelectedItem());
            stat.setInt(3, (Integer) lantai.getValue());
            stat.setInt(4, (Integer) kapasitas.getValue());
            stat.setString(5, fasilitas.getText());
            String status = tersedia.isSelected() ? "Tersedia" : "Sedang digunakan";
            stat.setString(6, status);
            stat.setString(7, kdruangan.getText());
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil diubah");
            dashboard.showPanel(new panelTampilRuangan(dashboard));
        } catch (SQLException e) {
          
            JOptionPane.showMessageDialog(null, "Data gagal diubah: " + e.getMessage());
        }
    }//GEN-LAST:event_bubahActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bbatal;
    private javax.swing.JButton bubah;
    private javax.swing.JRadioButton digunakan;
    private javax.swing.JTextArea fasilitas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jenis;
    private javax.swing.JSpinner kapasitas;
    private javax.swing.JTextField kdruangan;
    private javax.swing.JSpinner lantai;
    private javax.swing.JTextField nmruangan;
    private javax.swing.JRadioButton tersedia;
    // End of variables declaration//GEN-END:variables
}
