/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tampilan;

/**
 *
 * @author Aldi
 */
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.Koneksi;
public class panelTampilObat extends javax.swing.JPanel {
    private dashboard3 dashboard;
    private Connection conn = new Koneksi().connect();
    private DefaultTableModel tabmode;
    /**
     * Creates new form panelTampilObat
     */
    public panelTampilObat(dashboard3 dashboard) {
        initComponents();
        datatable();
        this.dashboard = dashboard;
    }
    
     protected void datatable() {
        Object[] Baris = {"Kd Obat", "Nama Obat", "Kategori", "Satuan", "Harga", "Stok"};
        tabmode = new DefaultTableModel(null, Baris);
        tabelobat.setModel(tabmode);
        String sql = "select * from obat where 1=1";
        if (!kdobat.getText().isEmpty()) {
            sql += " and kd_obat like '%" + kdobat.getText() + "%'";
        }
        if (!nmobat.getText().isEmpty()) {
            sql += " and nm_obat like '%" + nmobat.getText() + "%'";
        }
        if (kategori.getSelectedIndex() > 0) {
            sql += " and kategori = '" + kategori.getSelectedItem().toString() + "'";
        }
        if (!stok.getText().isEmpty()) {
            sql += " and stok = '" + stok.getText() + "'";
        }
        try {
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()) {
                tabmode.addRow(new Object[]{
                    hasil.getString("kd_obat"),
                    hasil.getString("nm_obat"),
                    hasil.getString("kategori"),
                    hasil.getString("satuan"),
                    hasil.getString("harga"),
                    hasil.getString("stok")
                });
            }
            tabelobat.setModel(tabmode);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "data gagal dipanggil" + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        kdobat = new javax.swing.JTextField();
        btambah = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelobat = new javax.swing.JTable();
        bcari = new javax.swing.JButton();
        bubah = new javax.swing.JButton();
        bhapus = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        nmobat = new javax.swing.JTextField();
        kategori = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        stok = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(244, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1366, 768));
        jPanel1.setMinimumSize(new java.awt.Dimension(1366, 768));
        jPanel1.setPreferredSize(new java.awt.Dimension(705, 441));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 28)); // NOI18N
        jLabel1.setText("Data Obat");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel2.setText("Kode Obat");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 84, -1));

        kdobat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        kdobat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                kdobatKeyPressed(evt);
            }
        });
        jPanel1.add(kdobat, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 150, -1));

        btambah.setBackground(new java.awt.Color(0, 153, 0));
        btambah.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btambah.setForeground(new java.awt.Color(255, 255, 255));
        btambah.setText("Tambah Data Obat");
        btambah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btambahActionPerformed(evt);
            }
        });
        jPanel1.add(btambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 490, -1, -1));

        tabelobat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tabelobat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Kd Obat", "Nama Obat", "Kategori", "Satuan", "Harga", "Stok"
            }
        ));
        jScrollPane1.setViewportView(tabelobat);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 689, 263));

        bcari.setBackground(new java.awt.Color(0, 153, 0));
        bcari.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        bcari.setForeground(new java.awt.Color(255, 255, 255));
        bcari.setText("Terapkan Filter");
        bcari.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcariActionPerformed(evt);
            }
        });
        jPanel1.add(bcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, -1, -1));

        bubah.setBackground(new java.awt.Color(0, 153, 0));
        bubah.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        bubah.setForeground(new java.awt.Color(255, 255, 255));
        bubah.setText("Ubah");
        bubah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bubahActionPerformed(evt);
            }
        });
        jPanel1.add(bubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 490, -1, -1));

        bhapus.setBackground(new java.awt.Color(255, 51, 51));
        bhapus.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        bhapus.setForeground(new java.awt.Color(255, 255, 255));
        bhapus.setText("Hapus");
        bhapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhapusActionPerformed(evt);
            }
        });
        jPanel1.add(bhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 490, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel3.setText("Nama Obat");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, -1, -1));

        nmobat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nmobat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nmobatKeyPressed(evt);
            }
        });
        jPanel1.add(nmobat, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 164, -1));

        kategori.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        kategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih Kategori Obat--", "Anallgesik", "Antibiotik", "Anti-inflamasi", "Bronkodilator", "Antihistamin", "Vitamin", " " }));
        kategori.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(kategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel4.setText("Kategori");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 100, -1));

        stok.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        stok.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                stokKeyPressed(evt);
            }
        });
        jPanel1.add(stok, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 130, 110, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel5.setText("Stok");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 100, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 950));
    }// </editor-fold>//GEN-END:initComponents

    private void kdobatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kdobatKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            datatable();
        }
    }//GEN-LAST:event_kdobatKeyPressed

    private void btambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btambahActionPerformed
        dashboard.showPanel(new panelTambahObat(dashboard));
    }//GEN-LAST:event_btambahActionPerformed

    private void bcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcariActionPerformed
        // TODO add your handling code here:
        datatable();
    }//GEN-LAST:event_bcariActionPerformed

    private void bubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bubahActionPerformed
        // TODO add your handling code here:
        int bar = tabelobat.getSelectedRow();
        if (bar == -1) {
            JOptionPane.showMessageDialog(null, "pilih data obat yang ingin diubah");
            return;
        }
        String kdobat = tabmode.getValueAt(bar, 0).toString();
        String nmobat = tabmode.getValueAt(bar, 1).toString();
        String kategori = tabmode.getValueAt(bar, 2).toString();
        String satuan = tabmode.getValueAt(bar, 3).toString();
        String harga = tabmode.getValueAt(bar, 4).toString();
        String stok = tabmode.getValueAt(bar, 5).toString();
        panelEditObat panel = new panelEditObat(dashboard);
        panel.setObat(kdobat, nmobat, kategori, satuan, harga, stok);
        dashboard.showPanel(panel);
    }//GEN-LAST:event_bubahActionPerformed

    private void bhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapusActionPerformed
        // TODO add your handling code here:
        int bar = tabelobat.getSelectedRow();
        if (bar == -1) {
            JOptionPane.showMessageDialog(null, "pilih data obat yang ingin dihapus");
            return;
        }
        String kdobat = tabmode.getValueAt(bar, 0).toString();
        int ok = JOptionPane.showConfirmDialog(null, "hapus", "konfirmasi dialog", JOptionPane.YES_NO_OPTION);
        if (ok == 0) {
            String sql = "delete from obat where kd_obat='" + kdobat + "'";
            try {
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "data berhasil dihapus");
                datatable();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "data gagal dihapus" + e);
            }
        }
    }//GEN-LAST:event_bhapusActionPerformed

    private void nmobatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nmobatKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_nmobatKeyPressed

    private void stokKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_stokKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_stokKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bcari;
    private javax.swing.JButton bhapus;
    private javax.swing.JButton btambah;
    private javax.swing.JButton bubah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> kategori;
    private javax.swing.JTextField kdobat;
    private javax.swing.JTextField nmobat;
    private javax.swing.JTextField stok;
    private javax.swing.JTable tabelobat;
    // End of variables declaration//GEN-END:variables
}
