/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tampilan;

/**
 *
 * @author Aldi
 */
import java.sql.*;
import javax.swing.JOptionPane;
import koneksi.Koneksi;
public class panelTambahPerawat extends javax.swing.JPanel {
    private dashboard3 dashboard;
    private Connection conn = new Koneksi().connect();
    /**
     * Creates new form panelTambahPerawat
     */
    public panelTambahPerawat(dashboard3 dashboard) {
        initComponents();
        this.dashboard = dashboard;
        
        aktif();
        kosong();
        isispesialis();
    }
    
     protected void aktif(){
        tkdperawat.requestFocus();
    }
    
    protected void kosong(){
        tkdperawat.setText("");
        tnmperawat.setText("");
        tnotelp.setText("");
        talamat.setText("");
        buttonGroup1.clearSelection();
        cbspesialis.setSelectedIndex(0);
    }
    
    protected void isispesialis(){
        cbspesialis.removeAllItems();
        cbspesialis.addItem("Spesialis Keperawatan Anak");
        cbspesialis.addItem("Spesialis Keperawatan Medikal Bedah");
        cbspesialis.addItem("Spesialis Keperawatan Gawat Darurat");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tkdperawat = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        tnmperawat = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        cbspesialis = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        rblaki = new javax.swing.JRadioButton();
        rbperempuan = new javax.swing.JRadioButton();
        jLabel20 = new javax.swing.JLabel();
        tnotelp = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        talamat = new javax.swing.JTextArea();
        bsimpan = new javax.swing.JButton();
        bbatal = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(244, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setMaximumSize(new java.awt.Dimension(1366, 768));
        jPanel1.setMinimumSize(new java.awt.Dimension(1366, 768));
        jPanel1.setPreferredSize(new java.awt.Dimension(559, 331));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Segoe UI Semibold", 0, 28)); // NOI18N
        jLabel15.setText("Tambah Data Perawat Baru");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 350, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel16.setText("Kd Perawat");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 100, -1));

        tkdperawat.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jPanel1.add(tkdperawat, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 180, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel17.setText("Nama Perawat");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 100, -1));

        tnmperawat.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jPanel1.add(tnmperawat, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 180, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel18.setText("Spesialis");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 100, -1));

        cbspesialis.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        cbspesialis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semua Spesialis", "Spesialis Keperawatan Anak", "Spesialis Keperawatan Medikal Bedah", "Spesialis Keperawatan Gawat Darurat", " " }));
        jPanel1.add(cbspesialis, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 216, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel19.setText("Jenis Kelamin");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 100, -1));

        buttonGroup1.add(rblaki);
        rblaki.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        rblaki.setText("Laki-Laki");
        jPanel1.add(rblaki, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 98, -1));

        buttonGroup1.add(rbperempuan);
        rbperempuan.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        rbperempuan.setText("Perempuan");
        jPanel1.add(rbperempuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 110, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel20.setText("No. Telp");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 80, -1));

        tnotelp.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        tnotelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnotelpActionPerformed(evt);
            }
        });
        jPanel1.add(tnotelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 180, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel21.setText("Alamat");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 60, -1));

        talamat.setColumns(20);
        talamat.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        talamat.setRows(5);
        jScrollPane3.setViewportView(talamat);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 242, -1));

        bsimpan.setBackground(new java.awt.Color(0, 153, 0));
        bsimpan.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        bsimpan.setForeground(new java.awt.Color(255, 255, 255));
        bsimpan.setText("Simpan");
        bsimpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsimpanActionPerformed(evt);
            }
        });
        jPanel1.add(bsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        bbatal.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        bbatal.setText("Batal");
        bbatal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbatalActionPerformed(evt);
            }
        });
        jPanel1.add(bbatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 950));
    }// </editor-fold>//GEN-END:initComponents

    private void tnotelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnotelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnotelpActionPerformed

    private void bsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpanActionPerformed
        // TODO add your handling code here:
        String jenis = null;
        if (rblaki.isSelected()){
            jenis = "Laki-Laki";
        } else if (rbperempuan.isSelected()){
            jenis = "Perempuan";
        }
        String sql = "insert into perawat (id_perawat, nama_perawat, jenis_kelamin, no_hp, spesialis, alamat) values (?,?,?,?,?,?)";
        try {
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, tkdperawat.getText());
            stat.setString(2, tnmperawat.getText());
            stat.setString(3, jenis);
            stat.setString(4, tnotelp.getText());
            stat.setString(5, (String) cbspesialis.getSelectedItem());
            stat.setString(6, talamat.getText());

            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "data berhasil disimpan");
            tkdperawat.requestFocus();
            dashboard.showPanel(new panelTampilPerawat(dashboard));
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "data gagal disimpan" + e);
        }
    }//GEN-LAST:event_bsimpanActionPerformed

    private void bbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbatalActionPerformed
        dashboard.showPanel(new panelTampilPerawat(dashboard));
        tkdperawat.requestFocus();
    }//GEN-LAST:event_bbatalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bbatal;
    private javax.swing.JButton bsimpan;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbspesialis;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton rblaki;
    private javax.swing.JRadioButton rbperempuan;
    private javax.swing.JTextArea talamat;
    private javax.swing.JTextField tkdperawat;
    private javax.swing.JTextField tnmperawat;
    private javax.swing.JTextField tnotelp;
    // End of variables declaration//GEN-END:variables
}
