/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tampilan;

/**
 *
 * @author Aldi
 */
import java.sql.*;
import javax.swing.JOptionPane;
import koneksi.Koneksi;
public class panelEditPerawat extends javax.swing.JPanel {
    private dashboard3 dashboard;
    private Connection conn = new Koneksi().connect();
    /**
     * Creates new form panelEditPerawat
     */
    public panelEditPerawat(dashboard3 dashboard) {
        initComponents();
        this.dashboard = dashboard;
    }
    
     public void setData(String kd, String nama, String jk, String telp, String spesialis, String alamat){

    tkdperawat.setText(kd);
    tnmperawat.setText(nama);
    tnotelp.setText(telp);
    cbspesialis.setSelectedItem(spesialis);
    talamat.setText(alamat);

    if(jk.equalsIgnoreCase("Laki-Laki")){
        rblaki.setSelected(true);
    }else{
        rbperempuan.setSelected(true);
    }

    tkdperawat.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tkdperawat = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        tnmperawat = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        cbspesialis = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        rblaki = new javax.swing.JRadioButton();
        rbperempuan = new javax.swing.JRadioButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        talamat = new javax.swing.JTextArea();
        bubah = new javax.swing.JButton();
        bbatal = new javax.swing.JButton();
        tnotelp = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(244, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1366, 768));
        jPanel1.setMinimumSize(new java.awt.Dimension(1366, 768));
        jPanel1.setPreferredSize(new java.awt.Dimension(559, 331));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Segoe UI Semibold", 0, 28)); // NOI18N
        jLabel15.setText("Edit Data Perawat");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 230, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel16.setText("Kd Perawat");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 100, -1));

        tkdperawat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(tkdperawat, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 180, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel17.setText("Nama Perawat");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 100, -1));

        tnmperawat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(tnmperawat, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 180, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel18.setText("Spesialis");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 100, -1));

        cbspesialis.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbspesialis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semua Spesialis", "Spesialis Keperawatan Anak", "Spesialis Keperawatan Medikal Bedah", "Spesialis Keperawatan Gawat Darurat", " " }));
        jPanel1.add(cbspesialis, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 217, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel19.setText("Jenis Kelamin");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 100, -1));

        rblaki.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        rblaki.setText("Laki-Laki");
        jPanel1.add(rblaki, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 98, -1));

        rbperempuan.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        rbperempuan.setText("Perempuan");
        jPanel1.add(rbperempuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 100, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel20.setText("No. Telp");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 100, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel21.setText("Alamat");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 100, -1));

        talamat.setColumns(20);
        talamat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        talamat.setRows(5);
        jScrollPane3.setViewportView(talamat);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, 242, -1));

        bubah.setBackground(new java.awt.Color(0, 153, 0));
        bubah.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        bubah.setForeground(new java.awt.Color(255, 255, 255));
        bubah.setText("Ubah");
        bubah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bubahActionPerformed(evt);
            }
        });
        jPanel1.add(bubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, -1, -1));

        bbatal.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        bbatal.setText("Batal");
        bbatal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbatalActionPerformed(evt);
            }
        });
        jPanel1.add(bbatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, -1, -1));

        tnotelp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(tnotelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 180, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 950));
    }// </editor-fold>//GEN-END:initComponents

    private void bubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bubahActionPerformed
        // TODO add your handling code here:
        String jenis = null;
        if (rblaki.isSelected()){
            jenis = "Laki-Laki";
        } else if (rbperempuan.isSelected()){
            jenis = "Perempuan";
        }
        String sql = "update perawat set nama_perawat=?, jenis_kelamin=?, no_hp=?, spesialis=?, alamat=? where id_perawat=?";
        try {
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, tnmperawat.getText());
            stat.setString(2, jenis);
            stat.setString(3, tnotelp.getText());
            stat.setString(4, cbspesialis.getSelectedItem().toString());
            stat.setString(5, talamat.getText());
            stat.setString(6, tkdperawat.getText());

            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "data berhasil diubah");
            tkdperawat.requestFocus();
            dashboard.showPanel(new panelTampilPerawat(dashboard));
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "data gagal diubah" + e);
        }

    }//GEN-LAST:event_bubahActionPerformed

    private void bbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbatalActionPerformed
        dashboard.showPanel(new panelTampilPerawat(dashboard));
        tkdperawat.requestFocus();
    }//GEN-LAST:event_bbatalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bbatal;
    private javax.swing.JButton bubah;
    private javax.swing.JComboBox<String> cbspesialis;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton rblaki;
    private javax.swing.JRadioButton rbperempuan;
    private javax.swing.JTextArea talamat;
    private javax.swing.JTextField tkdperawat;
    private javax.swing.JTextField tnmperawat;
    private javax.swing.JTextField tnotelp;
    // End of variables declaration//GEN-END:variables
}
