/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tampilan;

/**
 *
 * @author Aldi
 */
import java.sql.*;
import javax.swing.JOptionPane;
import koneksi.Koneksi;
public class panelEditObat extends javax.swing.JPanel {
    private dashboard3 dashboard;
 private Connection conn = new Koneksi().connect();
    /**
     * Creates new form panelEditObat
     */
    public panelEditObat(dashboard3 dashboard) {
        initComponents();
        this.dashboard = dashboard;
    }
    
    public void setObat(String kdobat, String nmobat, String kategori, String satuan, String harga, String stok) {
        this.kdobat.setText(kdobat);
        this.nmobat.setText(nmobat);
        this.kategori.setSelectedItem(kategori);
        this.satuan.setText(satuan);
        this.harga.setText(harga);
        this.stok.setText(stok);

        this.kdobat.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        kdobat = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nmobat = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        kategori = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        bbatal = new javax.swing.JButton();
        bubah = new javax.swing.JButton();
        satuan = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        harga = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        stok = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(244, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1366, 768));
        jPanel1.setMinimumSize(new java.awt.Dimension(1366, 768));
        jPanel1.setPreferredSize(new java.awt.Dimension(559, 331));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 28)); // NOI18N
        jLabel1.setText("Edit Data Obat");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 190, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel2.setText("Kode Obat");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 80, -1));

        kdobat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(kdobat, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 180, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel3.setText("Nama Obat");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, -1, -1));

        nmobat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nmobat.setName(""); // NOI18N
        jPanel1.add(nmobat, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 180, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel4.setText("Kategori");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 60, -1));

        kategori.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        kategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih Kategori Obat--", "Anallgesik", "Antibiotik", "Anti-inflamasi", "Bronkodilator", "Antihistamin", "Vitamin", " " }));
        kategori.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(kategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 180, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel6.setText("Satuan");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 50, -1));

        bbatal.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        bbatal.setText("Batal");
        bbatal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbatalActionPerformed(evt);
            }
        });
        jPanel1.add(bbatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, -1, 30));

        bubah.setBackground(new java.awt.Color(0, 153, 0));
        bubah.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        bubah.setForeground(new java.awt.Color(255, 255, 255));
        bubah.setText("Ubah");
        bubah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bubahActionPerformed(evt);
            }
        });
        jPanel1.add(bubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        satuan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(satuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 180, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel7.setText("Harga");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 50, -1));

        harga.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 180, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel8.setText("Stok");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 40, -1));

        stok.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(stok, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 180, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 950));
    }// </editor-fold>//GEN-END:initComponents

    private void bbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbatalActionPerformed
        dashboard.showPanel(new panelTampilObat(dashboard));
        kdobat.requestFocus();
    }//GEN-LAST:event_bbatalActionPerformed

    private void bubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bubahActionPerformed
        // TODO add your handling code here:
        String sql = "UPDATE obat SET nm_obat=?, kategori=?, satuan=?, harga=?, stok=? WHERE kd_obat=?";
        try (PreparedStatement stat = conn.prepareStatement(sql)) {
            stat.setString(1, nmobat.getText());
            stat.setString(2, (String) kategori.getSelectedItem());
            stat.setString(3, satuan.getText());
            stat.setString(4, harga.getText());
            stat.setString(5, stok.getText());
            stat.setString(6, kdobat.getText());
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil diubah");
            dashboard.showPanel(new panelTampilObat(dashboard));
            kdobat.requestFocus();
        } catch (SQLException e) {

            JOptionPane.showMessageDialog(null, "Data gagal diubah: " + e.getMessage());
            kdobat.requestFocus();
        }
    }//GEN-LAST:event_bubahActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bbatal;
    private javax.swing.JButton bubah;
    private javax.swing.JTextField harga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> kategori;
    private javax.swing.JTextField kdobat;
    private javax.swing.JTextField nmobat;
    private javax.swing.JTextField satuan;
    private javax.swing.JTextField stok;
    // End of variables declaration//GEN-END:variables
}
