/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tampilan;

/**
 *
 * @author Aldi
 */
import java.sql.*;
import javax.swing.JOptionPane;
import koneksi.Koneksi;
public class panelTambahRuangan extends javax.swing.JPanel {
    private dashboard3 dashboard;
    private Connection conn = new Koneksi().connect();
    /**
     * Creates new form panelTambahRuangan
     */
    public panelTambahRuangan(dashboard3 dashboard) {
        initComponents();
        this.dashboard = dashboard;
        
        aktif();
        kosong();
        isijenis();
    }
    
    protected void aktif() {
        kdruangan.requestFocus();
    }

    protected void kosong() {
        kdruangan.setText("");
        nmruangan.setText("");
        jenis.setSelectedIndex(0);
        lantai.setValue(1);
        kapasitas.setValue(1);
        fasilitas.setText("");
        tersedia.setSelected(false);
        digunakan.setSelected(false);
    }

    protected void isijenis() {
        jenis.removeAllItems();
        jenis.addItem("--Pilih Jenis Ruangan--");
        jenis.addItem("Rawat Inap");
        jenis.addItem("Poliklinik");
        jenis.addItem("IGD");
        jenis.addItem("Kritis");
        jenis.addItem("Operasi");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        kdruangan = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nmruangan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jenis = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        bbatal = new javax.swing.JButton();
        bsimpan = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        lantai = new javax.swing.JSpinner();
        kapasitas = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        fasilitas = new javax.swing.JTextArea();
        tersedia = new javax.swing.JRadioButton();
        digunakan = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(244, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1366, 768));
        jPanel1.setMinimumSize(new java.awt.Dimension(1366, 768));
        jPanel1.setPreferredSize(new java.awt.Dimension(559, 331));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 28)); // NOI18N
        jLabel1.setText("Tambah Data Ruangan Baru");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel2.setText("Kode Ruangan");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 100, -1));

        kdruangan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        kdruangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kdruanganActionPerformed(evt);
            }
        });
        jPanel1.add(kdruangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 180, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel3.setText("Nama Ruangan");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        nmruangan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nmruangan.setName(""); // NOI18N
        jPanel1.add(nmruangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 180, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel4.setText("Jenis Ruangan");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 100, -1));

        jenis.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih Jenis Ruangan--", "Rawat Inap", "Poliklinik", "IGD", "Kritis", "Operasi" }));
        jPanel1.add(jenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 180, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel6.setText("Lantai");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 50, -1));

        bbatal.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        bbatal.setText("Batal");
        bbatal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbatalActionPerformed(evt);
            }
        });
        jPanel1.add(bbatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, 80, -1));

        bsimpan.setBackground(new java.awt.Color(0, 153, 0));
        bsimpan.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        bsimpan.setForeground(new java.awt.Color(255, 255, 255));
        bsimpan.setText("Simpan");
        bsimpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsimpanActionPerformed(evt);
            }
        });
        jPanel1.add(bsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel7.setText("Kapasitas");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 80, -1));

        lantai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lantai.setModel(new javax.swing.SpinnerNumberModel(1, 0, 4, 1));
        jPanel1.add(lantai, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 180, -1));

        kapasitas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        kapasitas.setModel(new javax.swing.SpinnerNumberModel(1, 0, 5, 1));
        jPanel1.add(kapasitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 180, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel5.setText("Fasilitas");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, -1, -1));

        fasilitas.setColumns(20);
        fasilitas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fasilitas.setRows(5);
        jScrollPane1.setViewportView(fasilitas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 180, 149));

        tersedia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tersedia.setText("Tersedia");
        jPanel1.add(tersedia, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, -1, -1));

        digunakan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        digunakan.setText("Sedang digunakan");
        jPanel1.add(digunakan, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 380, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel8.setText("Status");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 950));
    }// </editor-fold>//GEN-END:initComponents

    private void kdruanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kdruanganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kdruanganActionPerformed

    private void bbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbatalActionPerformed
        dashboard.showPanel(new panelTampilRuangan(dashboard));
        kosong();
        kdruangan.requestFocus();
    }//GEN-LAST:event_bbatalActionPerformed

    private void bsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpanActionPerformed
        // TODO add your handling code here:
        String status = "";
        if (tersedia.isSelected()) {
            status = "Tersedia";
        } else if (digunakan.isSelected()) {
            status = "Sedang digunakan";
        }
        try {
            String sql = "INSERT INTO ruangan (kd_ruangan, nama_ruangan, jenis, lantai, kapasitas, fasilitas, status) VALUES (?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, kdruangan.getText());
            stat.setString(2, nmruangan.getText());
            stat.setString(3, jenis.getSelectedItem().toString());
            stat.setObject(4, lantai.getValue());
            stat.setObject(5, kapasitas.getValue());
            stat.setString(6, fasilitas.getText());
            stat.setString(7, status);
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
             kdruangan.requestFocus();
            dashboard.showPanel(new panelTampilRuangan(dashboard));
           
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data gagal disimpan" + e);
        }
    }//GEN-LAST:event_bsimpanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bbatal;
    private javax.swing.JButton bsimpan;
    private javax.swing.JRadioButton digunakan;
    private javax.swing.JTextArea fasilitas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jenis;
    private javax.swing.JSpinner kapasitas;
    private javax.swing.JTextField kdruangan;
    private javax.swing.JSpinner lantai;
    private javax.swing.JTextField nmruangan;
    private javax.swing.JRadioButton tersedia;
    // End of variables declaration//GEN-END:variables
}
